/***

   Copyright (C) 2018-2019. dc-koromo. All Rights Reserved.
   
   Author: Koromo Copy Developer

***/

namespace Koromo_Copy.Component.Hitomi.Translate
{
    public static class KoreanTag
    {
        public static string TagMap(string eng_tag)
        {
            switch (eng_tag)
            {
                case "group": return "그룹";
                case "mosaic censorship": return "모자이크 검열";
                case "incest": return "근친";
                case "full color": return "풀컬러";
                case "tankoubon": return "단행본";
                case "ffm threesome": return "여여남 쓰리썸";
                case "full censorship": return "완전 검열";
                case "mmf threesome": return "남남여 쓰리썸";
                case "story arc": return "스토리 아크";
                case "uncensored": return "미검열";
                case "multi-work series": return "시리즈물";
                case "anthology": return "시집";
                case "replaced": return "대체됨";
                case "webtoon": return "웹툰";
                case "incomplete": return "미완성";
                case "inseki": return "inseki";
                case "scanmark": return "스캔 마크";
                case "sample": return "샘플";
                case "rewrite": return "재작성";
                case "novel": return "소설";
                case "animated": return "애니";
                case "artbook": return "아트북";
                case "body swap": return "신체교환";
                case "out of order": return "정리되지 않음";
                case "time stop": return "시간 정지";
                case "missing cover": return "커버 없음";
                case "monster": return "몬스터";
                case "mtf threesome": return "남여트젠 쓰리썸";
                case "3d": return "3D";
                case "twins": return "쌍둥이";
                case "ttm threesome": return "남트젠트젠 쓰리썸";
                case "compilation": return "모음집";
                case "oyakodon": return "모녀덮밥";
                case "poor grammar": return "맞춤법 안맞음";
                case "watermarked": return "워터마크";
                case "game sprite": return "game sprite";
                case "mmt threesome": return "남남트젠 쓰리썸";
                case "miyamoto smoke": return "miyamoto smoke";
                case "variant set": return "variant set";
                case "tuna empire": return "tuna empire";
                case "nudity only": return "nudity only";
                case "comedy": return "코미디";
                case "levi": return "levi";
                case "frottage": return "프로타주";
                case "meganekko": return "meganekko";
                case "husky guy": return "husky guy";
                case "roman shoten": return "roman shoten";
                case "shinozuka jouji": return "shinozuka jouji";
                case "animal on animal": return "animal on animal";
                case "redraw": return "redraw";
                case "chiyou yoyuchi": return "chiyou yoyuchi";
                case "takuji": return "takuji";
                case "horror": return "호러";
                case "manga": return "망가";
                case "female:big breasts": return "female:거유";
                case "female:loli": return "female:로리";
                case "female:stockings": return "female:스타킹";
                case "female:schoolgirl uniform": return "female:여학생 교복";
                case "female:sole female": return "female:단독여성";
                case "female:anal": return "female:애널";
                case "female:nakadashi": return "female:질내 사정";
                case "female:bondage": return "female:속박";
                case "female:blowjob": return "female:펠라치오";
                case "female:rape": return "female:강간";
                case "female:glasses": return "female:안경";
                case "female:ahegao": return "female:아헤가오";
                case "female:paizuri": return "female:파이즈리";
                case "female:defloration": return "female:첫 경험";
                case "female:double penetration": return "female:동시 삽입";
                case "female:milf": return "female:밀프";
                case "female:sex toys": return "female:섹스 토이";
                case "female:futanari": return "female:후타나리";
                case "female:x-ray": return "female:투시";
                case "female:swimsuit": return "female:수영복";
                case "female:yuri": return "female:백합";
                case "female:femdom": return "female:펨돔";
                case "female:tentacles": return "female:촉수";
                case "female:impregnation": return "female:수정";
                case "female:sister": return "female:자매";
                case "female:netorare": return "female:네토라레";
                case "female:pregnant": return "female:임신";
                case "female:pantyhose": return "female:팬티 스타킹";
                case "female:mind break": return "female:타락";
                case "female:lactation": return "female:수유";
                case "female:dark skin": return "female:검은 피부";
                case "female:collar": return "female:목걸이";
                case "female:footjob": return "female:풋잡";
                case "female:maid": return "female:메이드";
                case "female:big ass": return "female:큰 엉덩이";
                case "female:bikini": return "female:비키니";
                case "female:cheating": return "female:불륜";
                case "female:urination": return "female:방뇨";
                //case "female:mother": return "female:mother"; ㅗ
                case "female:catgirl": return "female:고양이 소녀";
                case "female:gag": return "female:개그";
                case "female:masturbation": return "female:자위";
                case "female:handjob": return "female:핸드잡";
                case "female:exhibitionism": return "female:노출증";
                case "female:garter belt": return "female:가터 벨트";
                case "female:mind control": return "female:마인드 컨트롤";
                case "female:huge breasts": return "female:거대한 가슴";
                case "female:bloomers": return "female:블루머";
                case "female:small breasts": return "female:빈유";
                case "female:bukkake": return "female:부카케";
                case "female:scat": return "female:스캇";
                case "female:females only": return "female:여성만";
                case "female:hairy": return "female:털많은";
                case "female:harem": return "female:하렘";
                case "female:blindfold": return "female:눈가리개";
                case "female:inflation": return "female:팽창";
                case "female:teacher": return "female:선생님";
                case "female:lingerie": return "female:란제리";
                case "female:demon girl": return "female:악마 소녀";
                case "female:piercing": return "female:피어씽";
                case "female:bbw": return "female:뚱녀";
                case "female:bunny girl": return "female:토끼 소녀";
                case "female:elf": return "female:엘프";
                case "female:tanlines": return "female:선탠 라인";
                case "female:drugs": return "female:약물";
                case "female:kimono": return "female:기모노";
                case "female:bestiality": return "female:수간";
                case "female:fingering": return "female:성적 쾌감을 위해 손가락을 사용";
                case "female:stomach deformation": return "female:너무 큰 생식기나 물건이 들어가서 복부가 과장되게 튀어나옴";
                case "female:prostitution": return "female:매춘";
                case "female:school swimsuit": return "female:학교 수영복";
                case "female:cunnilingus": return "female:커닐링구스";
                case "female:enema": return "female:관장";
                case "female:unusual pupils": return "female:눈의 동공에 하트나 별 같은 특별한 모양이 있음";
                case "female:nurse": return "female:간호사";
                //case "female:strap-on": return "female:strap-on";
                case "female:monster girl": return "female:여성 몬스터";
                case "female:sweating": return "female:땀";
                case "female:birth": return "female:출산";
                case "female:sleeping": return "female:수면";
                case "female:spanking": return "female:스팽킹";
                case "female:rimjob": return "female:항문 빨기";
                case "female:miko": return "female:무녀";
                case "female:apron": return "female:에이프런";
                case "female:blackmail": return "female:협박";
                case "female:deepthroat": return "female:딥 펠라치오";
                case "female:kissing": return "female:키스";
                case "female:daughter": return "female:딸";
                case "female:bodysuit": return "female:바디슈트";
                case "female:big penis": return "female:큰 자지";
                case "female:schoolgirl": return "female:여학생";
                case "female:shibari": return "female:귀갑묶기";
                case "female:thigh high boots": return "female:무릎까지 오는 부츠";
                case "female:breast expansion": return "female:가슴이 커짐";
                case "female:furry": return "female:수인";
                case "female:gyaru": return "female:갸루";
                case "female:dick growth": return "female:자지가 커짐";
                case "female:slave": return "female:노예";
                case "female:latex": return "female:라텍스";
                case "female:leotard": return "female:레오타드";
                case "female:big areolae": return "female:큰 유륜";
                case "female:filming": return "female:촬영";
                case "female:magical girl": return "female:마법 소녀";
                case "female:cervix penetration": return "female:자궁에 직접적으로 성기를 삽입";
                case "female:guro": return "female:고어";
                case "female:corruption": return "female:타락";
                case "female:hairy armpits": return "female:겨털";
                //case "female:nipple fuck": return "female:nipple fuck";
                case "female:chloroform": return "female:클로로포름";
                case "female:bike shorts": return "female:스패츠";
                case "female:fisting": return "female:피스팅";
                case "female:urethra insertion": return "female:요도 삽입";
                //case "female:dickgirl on dickgirl": return "female:dickgirl on dickgirl";
                case "female:tiara": return "female:티아라";
                case "female:fox girl": return "female:여우녀";
                case "female:inverted nipples": return "female:함몰유두";
                case "female:bdsm": return "female:BDSM";
                case "female:group": return "female:그룹";
                case "female:crossdressing": return "female:반대 성별의 옷을 입음";
                case "female:shemale": return "female:쉬메일";
                case "female:human pet": return "female:사람을 애완동물처럼 다룸";
                case "female:incest": return "female:근친";
                case "female:chikan": return "female:치한";
                case "female:tomboy": return "female:외모가 남자 같은 여자";
                case "female:big nipples": return "female:큰 유두";
                case "female:torture": return "female:고문";
                case "female:facesitting": return "female:얼굴에 앉음";
                case "female:leg lock": return "female:성행위 하는 상대방을 두 다리로 끌어앉음";
                case "female:gokkun": return "female:정액을 먹음";
                case "female:sole dickgirl": return "female:단독 후타나리";
                case "female:waitress": return "female:웨이트리스";
                case "female:oppai loli": return "female:로리거유";
                case "female:muscle": return "female:근육";
                //case "female:male on dickgirl": return "female:male on dickgirl";
                case "female:large insertions": return "female:큰 물건을 삽입";
                case "female:tribadism": return "female:가위치기";
                case "female:eggs": return "female:난생이거나 안에 알이 들어있음";
                case "female:body writing": return "female:몸에 글자 쓰기";
                case "female:business suit": return "female:비즈니스 정장";
                case "female:eyepatch": return "female:안대";
                case "female:shimapan": return "female:줄무늬 팬티";
                case "female:nun": return "female:수녀";
                case "female:hotpants": return "female:핫팬츠";
                case "female:ryona": return "female:료나";
                case "female:bride": return "female:웨딩 드레스";
                case "female:drunk": return "female:술에 취함";
                case "female:wings": return "female:날개";
                case "female:transformation": return "female:물리적, 생물적 변화를 자세히 묘사함";
                case "female:squirting": return "female:시오후키";
                case "female:humiliation": return "female:굴욕";
                case "female:cousin": return "female:사촌";
                case "female:snuff": return "female:스너프";
                case "female:double vaginal": return "female:2개의 자지가 하나의 질로 삽입됨";
                case "female:tall girl": return "female:키가 큰 여성";
                case "female:armpit sex": return "female:겨드랑이로 성기를 자극함";
                case "female:triple penetration": return "female:3개의 구멍이 동시에 삽입당함";
                case "female:dog girl": return "female:멍멍이녀";
                case "female:breast feeding": return "female:가슴 빨기";
                case "female:blowjob face": return "female:펠라치오로 인해 양볼이 홀쭘해지는 얼굴모양";
                case "female:vore": return "female:보어물";
                case "female:cheerleader": return "female:치어리더";
                case "female:smell": return "female:강렬한 냄새를 방출함";
                case "female:milking": return "female:모유 채취";
                case "female:slime": return "female:슬라임";
                case "female:gaping": return "female:섹스 후 질 또는 항문이 늘어나 있는 모습";
                case "female:body modification": return "female:body 인체개조";
                case "female:cosplaying": return "female:코스프레";
                case "female:robot": return "female:로봇";
                case "female:sundress": return "female:여름용 원피스";
                case "female:angel": return "female:천사";
                case "female:prolapse": return "female:탈장";
                case "female:underwater": return "female:수중";
                case "female:twins": return "female:쌍둥이가 각자 다른 사람과 섹스함";
                case "female:yandere": return "female:얀데레";
                case "female:amputee": return "female:사지의 일부가 손실됨";
                case "female:military": return "female:밀리터리";
                case "female:kunoichi": return "female:쿠노이치";
                case "female:metal armor": return "female:중세 시대의 금속 갑옷";
                case "female:nose hook": return "female:코걸이";
                case "female:aunt": return "female:여자 연상 친척";
                case "female:giantess": return "female:거인녀";
                case "female:big clit": return "female:큰 클리토리스";
                case "female:possession": return "female:자신의 몸이 타인의 의지대로 움직임";
                case "female:corset": return "female:코르셋";
                case "female:diaper": return "female:기저귀";
                case "female:chinese dress": return "female:차이나 드레스";
                case "female:bisexual": return "female:양성 애자";
                case "female:piss drinking": return "female:소변 마심";
                case "female:public use": return "female:육변기";
                case "female:machine": return "female:기계와 섹스";
                case "female:oni": return "female:오니";
                case "female:parasite": return "female:기생충";
                case "female:cowgirl": return "female:젖소녀";
                case "female:all the way through": return "female:입이나 항문으로 물체가 삽입되어 반대편으로 나와서 몸을 관통함";
                case "female:witch": return "female:마녀";
                case "female:hairjob": return "female:머리카락으로 생식기를 자극";
                case "female:kemonomimi": return "female:동물귀";
                case "female:sumata": return "female:스마타"; // 사타구니에 성기를 비빔
                case "female:blood": return "female:출혈";
                case "female:wolf girl": return "female:늑대녀";
                case "female:solo action": return "female:본인이 직접 성적인 행위를 하면서 즐김";
                case "female:crotch tattoo": return "female:가랑이 문신";
                case "female:lab coat": return "female:연구복";
                case "female:tracksuit": return "female:운동복";
                case "female:christmas": return "female:크리스마스";
                case "female:insect": return "female:곤충";
                case "female:age progression": return "female:급격히 나이를 먹음";
                case "female:farting": return "female:방귀";
                case "female:policewoman": return "female:여자 경찰";
                //case "female:oyakodon": return "female:oyakodon";
                case "female:tail plug": return "female:꼬리 플러그";
                case "female:vomit": return "female:구토";
                case "female:gothic lolita": return "female:고스로리";
                case "female:mecha girl": return "female:기계 부품이 몸 밖으로 드러난 여자";
                case "female:vampire": return "female:뱀파이어";
                case "female:double anal": return "female:2개의 자지가 하나의 항문으로 들어감";
                case "female:pasties": return "female:젖꼭지 가리개";
                case "female:low lolicon": return "female:로리 내용이 있으나 비율이 적음";
                case "female:gender bender": return "female:성별 전환";
                case "female:randoseru": return "female:란도셀";
                case "female:assjob": return "female:엉덩이 틈 사이에 자지를 비빔";
                case "female:emotionless sex": return "female:무표정 섹스";
                case "female:toddlercon": return "female:유아";
                case "female:asphyxiation": return "female:질식";
                case "female:dougi": return "female:도복";
                case "female:armpit licking": return "female:겨드랑이 핥기";
                case "female:stuck in wall": return "female:벽에 끼어서 움직일 수 없음";
                case "female:dark nipples": return "female:흑두";
                case "female:full body tattoo": return "female:전신 문신";
                case "female:multiple paizuri": return "female:하나의 남성 생식기에 여러개의 가슴이 파이즈리";
                case "female:tickling": return "female:간지럼";
                case "female:fairy": return "female:요정";
                case "female:moral degeneration": return "female:섹스에 대한 도덕적 관념이 사라짐";
                //case "female:beauty mark": return "female:beauty mark";
                case "female:chastity belt": return "female:정조대";
                case "female:big balls": return "female:큰 불알";
                case "female:pillory": return "female:구속구";
                case "female:eyemask": return "female:눈가리개";
                case "female:huge penis": return "female:매우 큰 자지";
                case "female:orgasm denial": return "female:도구를 사용해 오르가즘에 도달하지 못하도록 함";
                case "female:minigirl": return "female:소인녀";
                case "female:swinging": return "female:커플중 한 명 또는 모두가 제3자와 섹스하는 것을 허락함";
                //case "female:coprophagia": return "female:똥 먹음";
                case "female:widow": return "female:과부";
                case "female:snake girl": return "female:뱀녀";
                case "female:ghost": return "female:유령";
                case "female:wooden horse": return "female:목마";
                case "female:tube": return "female:튜브";
                case "female:electric shocks": return "female:전기 충격";
                case "female:niece": return "female:여자조카";
                case "female:masked face": return "female:가면";
                case "female:selfcest": return "female:한 사람의 다른 두 버전이 서로 섹스함";
                case "female:ball sucking": return "female:불알 빨기";
                case "female:age regression": return "female:급격히 나이가 어려짐";
                case "female:brain fuck": return "female:뇌와 관련된 섹스";
                case "female:ponytail": return "female:포니테일";
                case "female:long tongue": return "female:긴 혀";
                case "female:autofellatio": return "female:셀프 펠라치오";
                case "female:wrestling": return "female:레슬링";
                case "female:foot licking": return "female:발을 핥음";
                case "female:twintails": return "female:트윈테일";
                case "female:speculum": return "female:질이나 항문을 벌리는 의학적 도구";
                case "female:freckles": return "female:주근깨";
                case "female:living clothes": return "female:살아 움직이는 옷";
                case "female:bandages": return "female:붕대가 몸의 상당부분을 가림";
                case "female:unbirth": return "female:질이나 항문으로 사람을 삼켜서 흡수함";
                case "female:slime girl": return "female:슬라임녀";
                case "female:double blowjob": return "female:2개의 자지가 하나의 입으로 들어감";
                case "female:voyeurism": return "female:관음증";
                case "female:pubic stubble": return "female:제모후 짧게 다시자란 음모";
                case "female:ttf threesome": return "female:여트젠트젠 쓰리썸";
                case "female:pantyjob": return "female:팬티잡";
                case "female:human cattle": return "female:사람을 가축처럼 다룸";
                case "female:mermaid": return "female:인어녀";
                case "female:clit growth": return "female:클리토리스가 커짐";
                case "female:whip": return "female:채찍";
                case "female:condom": return "female:콘돔";
                case "female:scar": return "female:흉터";
                case "female:zombie": return "female:좀비";
                case "female:fundoshi": return "female:훈도시";
                case "female:onahole": return "female:오나홀";
                case "female:clothed paizuri": return "female:옷입고 파이즈리";
                case "female:multiple penises": return "female:다수의 남성기";
                case "female:catfight": return "female:여자끼리 싸움";
                case "female:tutor": return "female:가정교사";
                case "female:tights": return "female:타이즈";
                case "female:smegma": return "female:치구";
                case "female:lizard girl": return "female:도마뱀 소녀";
                case "female:centaur": return "female:켄타우로스";
                case "female:body painting": return "female:바디페인팅";
                case "female:petrification": return "female:석화";
                case "female:multiple breasts": return "female:다수의 유방";
                case "female:crown": return "female:왕관";
                case "female:low bestiality": return "female:약간의 수간";
                case "female:glory hole": return "female:글로리 홀";
                case "female:gymshorts": return "female:운동바지";
                case "female:dicknipples": return "female:유두자지";
                case "female:harpy": return "female:하피";
                case "female:skinsuit": return "female:달라붙는 옷";
                case "female:sunglasses": return "female:선글라스";
                case "female:smoking": return "female:흡연";
                case "female:cum swap": return "female:채액 교환";
                case "female:bodystocking": return "female:바디스타킹";
                case "female:insect girl": return "female:곤충녀";
                case "female:oil": return "female:오일";
                case "female:vaginal sticker": return "female:마에바리";
                case "female:frottage": return "female:프로타주";
                case "female:nipple expansion": return "female:유두 팽창";
                case "female:cbt": return "female:Cbt";
                case "female:wormhole": return "female:웜홀";
                case "female:phimosis": return "female:포경";
                case "female:squid girl": return "female:오징어 소녀";
                case "female:plant girl": return "female:식물 소녀";
                case "female:weight gain": return "female:82kg 김지영씨";
                case "female:dickgirls only": return "female:후타라니만";
                case "female:mouse girl": return "female:마우스 소녀";
                case "female:gigantic breasts": return "female:졸라큰 가슴";
                case "female:heterochromia": return "female:얼룩증";
                case "female:table masturbation": return "female:책상자위";
                case "female:horse girl": return "female:말 소녀";
                case "female:dark sclera": return "female:검은 흰자";
                case "female:forniphilia": return "female:인간가구";
                case "female:schoolboy uniform": return "female:남학생 유니폼";
                case "female:syringe": return "female:주사기";
                case "female:mature": return "female:성숙한";
                case "female:spider girl": return "female:거미녀";
                case "female:human on furry": return "female:수인에게 인간이";
                case "female:snake": return "female:뱀";
                case "female:navel fuck": return "female:배꼽박이";
                case "female:fft threesome": return "female:여트젠트젠 쓰리썸";
                case "female:alien girl": return "female:외계 소녀";
                case "female:stewardess": return "female:스튜어디스";
                case "female:raccoon girl": return "female:너구리 소녀";
                case "female:ear fuck": return "female:귀에 삽입";
                case "female:octopus": return "female:문어";
                case "female:worm": return "female:벌레";
                case "female:doll joints": return "female:인형관절";
                case "female:sheep girl": return "female:양 소녀";
                case "female:wet clothes": return "female:젖은 옷";
                case "female:shared senses": return "female:감각공유";
                case "female:growth": return "female:거인화";
                case "female:absorption": return "female:흡수";
                //case "female:cashier": return "female:cashier";
                case "female:big vagina": return "female:허벌 보지";
                case "female:infantilism": return "female:유아적인행동";
                case "female:invisible": return "female:투명인간";
                case "female:stretching": return "female:스트레칭";
                case "female:saliva": return "female:침";
                case "female:handicapped": return "female:장애인";
                case "female:cum bath": return "female:정액 목욕";
                case "female:unusual teeth": return "female:특이한 이빨";
                case "female:coach": return "female:코치";
                case "female:autopaizuri": return "female:오토파이즈리";
                case "female:girls only": return "female:여자만";
                case "female:necrophilia": return "female:네크로필리아";
                case "female:anorexic": return "female:식용부진";
                case "female:pig girl": return "female:돼지녀";
                case "female:menstruation": return "female:생리혈";
                case "female:anal birth": return "female:애널 출생";
                case "female:tailjob": return "female:꼬리로 생식기를 자극";
                case "female:cannibalism": return "female:식인";
                case "female:pirate": return "female:해적";
                case "female:male on futanari": return "female:남자x후타나리";
                case "female:triple vaginal": return "female:3개의 자지 또는 3개의 성기구 등이 하나의 질에 삽입됨";
                case "female:eel": return "female:뱀장어 ";
                case "female:granddaughter": return "female:조부모와 손녀가";
                case "female:slug": return "female:복족류 연체동물";
                case "female:futanari on futanari": return "female:후타나리x후타나리";
                case "female:prostate massage": return "female:회음부 자극";
                case "female:ass expansion": return "female:엉덩이가 커짐";
                case "female:body swap": return "female:신체교환";
                case "female:nipple birth": return "female:젖꼭지 출생";
                case "female:pole dancing": return "female:봉춤";
                case "female:race queen": return "female:레이싱 모델";
                case "female:blind": return "female:눈가리개";
                case "female:dragon": return "female:드래곤";
                case "female:big lips": return "female:큰 입술";
                case "female:frog": return "female:개구리";
                case "female:eye penetration": return "female:눈에다 섹스";
                case "female:kigurumi": return "female:캐릭터를 나타내는 몸 전체를 뒤덮는 코스튬";
                case "female:shrinking": return "female:소인화";
                case "female:nose fuck": return "female:코에다 섹스";
                case "female:orc": return "female:오크";
                case "female:triple anal": return "female:3개의 자지가 하나의 아날로 들어감";
                case "female:multiple arms": return "female:팔이 3개 이상";
                case "female:prehensile hair": return "female:머리카락을 수족처럼 다룸";
                case "female:inseki": return "female:입양가족";
                case "female:ponygirl": return "female:포니걸";
                case "female:grandmother": return "female:할머니";
                case "female:midget": return "female:난쟁이";
                case "female:foot insertion": return "female:발을 삽입함";
                case "female:layer cake": return "female:보지 덮밥";
                case "female:cum in eye": return "female:눈에 정액 뿌리기";
                case "female:bandaid": return "female:무법자";
                case "female:phone sex": return "female:폰섹";
                case "female:horse": return "female:말";
                case "female:balls expansion": return "female:불알 확장";
                case "female:spider": return "female:거미";
                case "female:bee girl": return "female:꿀벌녀";
                case "female:vacbed": return "female:진공침대";
                case "female:balljob": return "female:불알에다가 하는 파이즈리";
                //case "female:clamp": return "female:clamp";
                case "female:kneepit sex": return "female:오금으로 자지나 유사한 물체를 자극함";
                case "female:squirrel girl": return "female:다람쥐녀";
                case "female:gasmask": return "female:방독면";
                case "female:monoeye": return "female:외눈박이";
                case "female:kindergarten uniform": return "female:유치원복";
                case "female:abortion": return "female:유산";
                case "female:trampling": return "female:발에 밟힘";
                case "female:old lady": return "female:50세 이상 여성";
                case "female:sockjob": return "female:양말플레이";
                case "female:maggot": return "female:구더기";
                //case "female:ssbbw": return "female:ssbbw";
                case "female:kappa": return "female:갓파";
                case "female:albino": return "female:백색증";
                case "female:nazi": return "female:나치";
                case "female:frog girl": return "female:개구리 소녀";
                case "female:horse cock": return "female:대물";
                case "female:monkey": return "female:원숭이";
                case "female:robot girl": return "female:로봇 소녀";
                case "female:scrotal lingerie": return "female:음낭 란제리";
                case "female:first person perspective": return "female:1인칭 시점";
                case "female:bald": return "female:대머리";
                case "female:hijab": return "female:히잡";
                case "female:dog": return "female:강아지";
                case "female:legjob": return "female:다리를 사용해 자극함";
                case "female:breast reduction": return "female:가슴이 작아짐";
                case "female:cow": return "female:젖소";
                case "female:tooth brushing": return "female:양치질";
                case "female:rabbit": return "female:토끼";
                case "female:burping": return "female:트림";
                //case "female:penis birth": return "female:penis birth";
                case "female:haigure": return "female:하이그레";
                case "female:cat": return "female:고양이";
                case "female:fox": return "female:여우";
                //case "female:forced": return "female:forced";
                case "female:mute": return "female:청각 장애인";
                //case "female:harness": return "female:harness";
                case "female:butler": return "female:집사";
                case "female:fish": return "female:물고기";
                case "female:pig": return "female:돼지";
                case "female:snail girl": return "female:뱀 소녀";
                case "female:goblin": return "female:고블린";
                case "female:multiple nipples": return "female:3개 이상의 젖꼭지";
                case "female:piercings": return "female:피어싱";
                case "female:muscle growth": return "female:근육이 생기거나 커짐";
                case "female:cockslapping": return "female:사람을 자지로 때림";
                case "female:tiger": return "female:호랑이";
                case "female:donkey": return "female:당나귀";
                case "female:panda girl": return "female:판다 소녀";
                case "female:mouse": return "female:쥐";
                case "female:adventitious vagina": return "female:이상한 곳에 질이 있음";
                case "female:reptile": return "female:파충류";
                case "female:shark girl": return "female:상어 소녀";
                case "female:conjoined": return "female:샴쌍둥이";
                case "female:dismantling": return "female:해체";
                case "female:lioness": return "female:암컷 사자";
                case "female:schoolboy": return "female:남학생";
                case "female:dolphin": return "female:돌고래";
                case "female:wolf": return "female:늑대";
                case "female:bear girl": return "female:곰 소녀";
                case "female:elephant": return "female:코끼리";
                case "female:animal on furry": return "female:동물x수인";
                case "female:gijinka": return "female:의인화";
                case "female:multiple vaginas": return "female:다수의 질";
                case "female:bear": return "female:곰";
                case "female:draenei": return "female:드레나이";
                case "female:sheep": return "female:양";
                case "female:closed eyes": return "female:감은 눈";
                case "female:kangaroo": return "female:캥거루";
                case "female:unicorn": return "female:유니콘";
                case "female:dinosaur": return "female:공룡";
                case "female:waiter": return "female:웨이터";
                case "female:school uniform": return "female:교복";
                case "female:blow job": return "female:펠라치오";
                case "female:gymshort": return "female:짧은 운동 용 바지";
                case "female:futa": return "female:후타";
                case "female:clown": return "female:광대";
                case "female:demon": return "female:악마";
                case "female:amputation": return "female:절단 ";
                //case "female:nose hooks": return "female:nose hooks";
                case "female:spats": return "female:스패츠";
                case "female:ogre": return "female:사람을 잡아먹는 거인";
                case "female:dragonfly": return "female:잠자리";
                case "female:stocking": return "female:스타킹";
                case "female:tail": return "female:꼬리";
                case "female:tall": return "female:큰 키";
                case "female:tattoo": return "female:타투";
                //case "female:throat bulging": return "female:throat bulging";
                case "female:maids": return "female:메이드";
                case "female:braces": return "female:치아 교정기";
                case "female:crab": return "female:게";
                case "female:irrumatio": return "female:이루마티오";
                case "female:insects": return "female:곤충";
                case "female:bandage": return "female:붕대가 몸의 상당부분을 가림";
                //case "female:shrink": return "female:shrink";
                case "female:larva": return "female:애벌레";
                case "female:lamia": return "female:반인반수 괴물";
                case "female:kneesock": return "female:니삭스";
                case "female:worms": return "female:웜";
                case "female:leeches": return "female:거머리";
                case "female:animal on animal": return "female:동물x동물";
                case "female:bf": return "female:bf";
                case "female:snails": return "female:뱀";
                case "male:sole male": return "male:단독남성";
                case "male:shota": return "male:쇼타";
                case "male:yaoi": return "male:야오이";
                case "male:anal": return "male:애널";
                case "male:glasses": return "male:안경";
                case "male:males only": return "male:남자만";
                case "male:dilf": return "male:아저씨";
                case "male:schoolboy uniform": return "male:남학생 교복";
                case "male:crossdressing": return "male:여장";
                case "male:bbm": return "male:뚱뚱한 남자";
                case "male:dark skin": return "male:검은피부";
                case "male:tomgirl": return "male:여자같은 남자";
                case "male:muscle": return "male:근육";
                case "male:gender bender": return "male:성전환";
                case "male:bondage": return "male:속박";
                case "male:big penis": return "male:큰 자지";
                case "male:monster": return "male:목스터";
                case "male:condom": return "male:콘돔";
                case "male:teacher": return "male:선생님";
                case "male:virginity": return "male:후장개통";
                case "male:furry": return "male:수인";
                case "male:blowjob": return "male:펠라치오";
                case "male:stockings": return "male:스타킹";
                case "male:military": return "male:밀리터리";
                case "male:rape": return "male:강간";
                case "male:group": return "male:그룹";
                case "male:harem": return "male:하렘";
                case "male:old man": return "male:노인";
                case "male:pegging": return "male:페깅";
                case "male:sex toys": return "male:섹스토이";
                case "male:cheating": return "male:불륜";
                //case "male:dickgirl on male": return "male:dickgirl on male";
                case "male:dog": return "male:개";
                case "male:prostate massage": return "male:전립선 마사지";
                case "male:ahegao": return "male:아헤가오";
                case "male:schoolgirl uniform": return "male:여학생 교복";
                case "male:masturbation": return "male:자위";
                case "male:nakadashi": return "male:애널사정";
                case "male:business suit": return "male:비지니스 정장";
                case "male:kimono": return "male:기모노";
                case "male:collar": return "male:목걸이";
                case "male:masked face": return "male:가면";
                case "male:demon": return "male:악마";
                case "male:blindfold": return "male:눈가리개";
                case "male:snuff": return "male:스너프";
                case "male:orc": return "male:오크";
                //case "male:cbt": return "male:cbt";
                case "male:catboy": return "male:캣 보이";
                case "male:foot licking": return "male:발을 핥음";
                case "male:exhibitionism": return "male:노출증";
                case "male:handjob": return "male:핸드잡";
                case "male:incest": return "male:근친";
                case "male:swimsuit": return "male:수영복";
                case "male:feminization": return "male:불완전 성전환";
                case "male:blood": return "male:피";
                case "male:bald": return "male:대머리";
                case "male:rimjob": return "male:애널핥기";
                case "male:urethra insertion": return "male:요도 삽입";
                case "male:mind break": return "male:타락";
                case "male:smegma": return "male:치구";
                case "male:drugs": return "male:약물";
                case "male:tentacles": return "male:촉수";
                case "male:urination": return "male:방뇨";
                case "male:orgasm denial": return "male:도구를 사용해 오르가즘에 도달하지 못하도록 함";
                case "male:tracksuit": return "male:운동복";
                case "male:sweating": return "male:땀";
                case "male:maid": return "male:메이드";
                case "male:brother": return "male:형제";
                case "male:human on furry": return "male:수인에게 인간이";
                case "male:gag": return "male:개그";
                case "male:netorare": return "male:네토라레";
                case "male:sunglasses": return "male:선글라스";
                case "male:horse": return "male:말";
                case "male:lingerie": return "male:란제리";
                case "male:tall man": return "male:키큰남자";
                case "male:tanlines": return "male:썬탠자국";
                case "male:sleeping": return "male:수면";
                case "male:frottage": return "male:프로타주";
                case "male:guro": return "male:고어";
                case "male:schoolboy": return "male:남학생";
                case "male:pig": return "male:돼지";
                case "male:mind control": return "male:마인드 컨트롤";
                case "male:voyeurism": return "male:관음증";
                case "male:onahole": return "male:오나홀";
                case "male:coach": return "male:코치";
                case "male:prostitution": return "male:매춘";
                case "male:scar": return "male:흉터";
                case "male:elf": return "male:엘프";
                case "male:kissing": return "male:키스";
                case "male:chastity belt": return "male:정조대";
                case "male:blackmail": return "male:협박";
                case "male:josou seme": return "male:여장이 공격";
                case "male:piss drinking": return "male:소변 마심";
                case "male:miniguy": return "male:작은남자";
                case "male:lab coat": return "male:연구복";
                case "male:unusual pupils": return "male:눈의 동공에 하트나 별 같은 특별한 모양이 있음";
                case "male:bunny boy": return "male:토끼남";
                case "male:x-ray": return "male:투시";
                case "male:ryona": return "male:료나";
                case "male:huge penis": return "male:큰 자지";
                case "male:humiliation": return "male:굴욕";
                case "male:footjob": return "male:풋잡";
                case "male:pantyhose": return "male:팬티 스타킹";
                case "male:wolf boy": return "male:늑대소년";
                case "male:bdsm": return "male:BDSM";
                case "male:dog boy": return "male:강아지 소년";
                case "male:bikini": return "male:비키니";
                case "male:eyepatch": return "male:안대";
                case "male:transformation": return "male:변신";
                case "male:spanking": return "male:스팽킹";
                case "male:eyemask": return "male:안대";
                case "male:scat": return "male:스캇";
                case "male:double anal": return "male:더블애널";
                case "male:guys only": return "male:남자만";
                case "male:pig man": return "male:돼지남";
                case "male:drunk": return "male:술에 취함";
                case "male:invisible": return "male:투명";
                case "male:double penetration": return "male:동시 삽입";
                case "male:torture": return "male:고문";
                case "male:bisexual": return "male:양성 애자";
                case "male:hairy": return "male:털많은";
                case "male:smell": return "male:냄세나는";
                case "male:slave": return "male:노예";
                case "male:tutor": return "male:가정교사";
                case "male:garter belt": return "male:가터벨트";
                case "male:zombie": return "male:좀비";
                case "male:gyaru-oh": return "male:갸루남";
                case "male:piercing": return "male:피어싱";
                case "male:cosplaying": return "male:코스프레";
                case "male:bestiality": return "male:수간";
                case "male:first person perspective": return "male:1인칭 시점";
                case "male:phimosis": return "male:포경";
                case "male:fox boy": return "male:여우 소년";
                case "male:school swimsuit": return "male:학교 수영복";
                case "male:goblin": return "male:고블린";
                case "male:vore": return "male:보어물";
                case "male:bandages": return "male:붕대가 몸의 상당부분을 가림";
                case "male:inflation": return "male:팽창";
                case "male:age regression": return "male:급격히 나이가 어려짐";
                case "male:dougi": return "male:도복";
                case "male:oni": return "male:오니";
                case "male:bodysuit": return "male:바디슈트";
                case "male:chikan": return "male:치한";
                case "male:father": return "male:아버지";
                case "male:dragon": return "male:드래곤";
                case "male:shibari": return "male:귀갑묶기";
                case "male:possession": return "male:자신의 몸이 타인의 의지대로 움직임";
                case "male:robot": return "male:로봇";
                case "male:bukkake": return "male:부카케";
                case "male:twins": return "male:쌍둥이";
                case "male:unbirth": return "male:질이나 항문으로 사람을 삼켜서 흡수함";
                case "male:filming": return "male:촬영";
                case "male:minotaur": return "male:미니어쳐";
                case "male:policeman": return "male:경찰";
                case "male:enema": return "male:관장";
                case "male:low shotacon": return "male:쇼타 내용이 있으나 비율이 적음";
                case "male:armpit licking": return "male:겨드랑이 핥기";
                case "male:butler": return "male:집사";
                case "male:apron": return "male:앞치마";
                case "male:bloomers": return "male:블루머";
                case "male:diaper": return "male:기저귀";
                case "male:dick growth": return "male:자지가 커짐";
                case "male:fundoshi": return "male:훈도시";
                case "male:bike shorts": return "male:스패츠";
                case "male:amputee": return "male:사지의 일부가 손실됨";
                case "male:giant": return "male:거인";
                case "male:lizard guy": return "male:도마뱀 남";
                case "male:layer cake": return "male:보지 덮밥";
                case "male:futanari on male": return "male:후타나리에게 박힘";
                case "male:full body tattoo": return "male:전신 문신";
                case "male:stomach deformation": return "male:너무 큰 생식기나 물건이 들어가서 복부가 과장되게 튀어나옴";
                case "male:gokkun": return "male:정액";
                case "male:ghost": return "male:귀신";
                case "male:alien": return "male:외계인";
                case "male:multiple penises": return "male:다수의 남성기";
                case "male:fisting": return "male:피스팅";
                case "male:lactation": return "male:수유";
                case "male:nurse": return "male:간호사";
                case "male:wolf": return "male:늑대";
                case "male:corruption": return "male:타락";
                case "male:horse boy": return "male:말 소년";
                case "male:asphyxiation": return "male:질식";
                case "male:freckles": return "male:주근깨";
                case "male:insect": return "male:곤충";
                case "male:selfcest": return "male:한 사람의 다른 두 버전이 서로 섹스함";
                case "male:waiter": return "male:웨이터";
                case "male:big balls": return "male:큰 불알";
                case "male:ninja": return "male:닌자";
                case "male:shrinking": return "male:소인화";
                case "male:latex": return "male:라텍스";
                case "male:leotard": return "male:레오타드";
                case "male:vampire": return "male:뱀파이어";
                case "male:facesitting": return "male:얼굴에 앉음";
                case "male:human pet": return "male:human 사람을 애완동물처럼 다룸";
                case "male:deepthroat": return "male:딥 펠라치오";
                case "male:tiara": return "male:왕관";
                case "male:metal armor": return "male:중세 시대의 금속 갑옷";
                case "male:slime": return "male:슬라임";
                case "male:big ass": return "male:큰 엉덩이";
                case "male:kemonomimi": return "male:동물귀";
                case "male:unusual teeth": return "male:특이한 이빨";
                case "male:sundress": return "male:여름용 원피스";
                case "male:pregnant": return "male:임신";
                case "male:gymshorts": return "male:운동바지";
                case "male:solo action": return "male:본인이 직접 성적인 행위를 하면서 즐김";
                case "male:shimapan": return "male:줄무늬 팬티";
                case "male:long tongue": return "male:긴 혀";
                case "male:christmas": return "male:크리스마스";
                case "male:yandere": return "male:얀데레";
                case "male:whip": return "male:채찍";
                case "male:chloroform": return "male:클로로포름";
                case "male:cheerleader": return "male:치어리더";
                case "male:bear boy": return "male:곰 소년";
                case "male:bull": return "male:황소";
                case "male:glory hole": return "male:글로리 홀";
                case "male:chinese dress": return "male:차이나 드레스";
                case "male:body swap": return "male:신체교환";
                case "male:angel": return "male:천사";
                case "male:inseki": return "male:입양가족";
                case "male:breast expansion": return "male:가슴 팽창";
                case "male:toddlercon": return "male:유아";
                case "male:bride": return "male:웨딩 드레스";
                case "male:monkey": return "male:원숭이";
                case "male:thigh high boots": return "male:무릎까지 오는 부츠";
                //case "male:coprophagia": return "male:coprophagia";
                case "male:priest": return "male:사제";
                case "male:infantilism": return "male:유아적인행동";
                case "male:autofellatio": return "male:셀프 펠라치오";
                case "male:gaping": return "male:섹스 후 질 또는 항문이 늘어나 있는 모습";
                case "male:cowman": return "male:cowman";
                case "male:cuntboy": return "male:cuntboy";
                case "male:impregnation": return "male:수정";
                case "male:bear": return "male:bear";
                case "male:schoolgirl": return "male:schoolgirl";
                case "male:double blowjob": return "male:double blowjob";
                case "male:cat": return "male:cat";
                case "male:leg lock": return "male:leg lock";
                case "male:wings": return "male:wings";
                case "male:age progression": return "male:age progression";
                case "male:uncle": return "male:uncle";
                case "male:sumata": return "male:sumata";
                case "male:breast feeding": return "male:breast feeding";
                case "male:tail plug": return "male:tail plug";
                case "male:big breasts": return "male:big breasts";
                case "male:hotpants": return "male:hotpants";
                case "male:snake": return "male:snake";
                case "male:moral degeneration": return "male:moral degeneration";
                case "male:public use": return "male:public use";
                case "male:underwater": return "male:underwater";
                case "male:large insertions": return "male:large insertions";
                case "male:magical girl": return "male:magical girl";
                case "male:corset": return "male:corset";
                case "male:miko": return "male:miko";
                case "male:gorilla": return "male:gorilla";
                case "male:necrophilia": return "male:necrophilia";
                case "male:vomit": return "male:vomit";
                case "male:cashier": return "male:cashier";
                case "male:oyakodon": return "male:oyakodon";
                case "male:skinsuit": return "male:skinsuit";
                case "male:waitress": return "male:waitress";
                case "male:eggs": return "male:eggs";
                case "male:cannibalism": return "male:cannibalism";
                case "male:frog": return "male:frog";
                case "male:parasite": return "male:parasite";
                case "male:kappa": return "male:kappa";
                case "male:body writing": return "male:body writing";
                case "male:octopus": return "male:octopus";
                case "male:stuck in wall": return "male:stuck in wall";
                case "male:shaved head": return "male:shaved head";
                case "male:midget": return "male:midget";
                case "male:dolphin": return "male:dolphin";
                case "male:gothic lolita": return "male:gothic lolita";
                case "male:wormhole": return "male:wormhole";
                case "male:tights": return "male:tights";
                case "male:oil": return "male:oil";
                case "male:reptile": return "male:reptile";
                case "male:wrestling": return "male:wrestling";
                case "male:big nipples": return "male:big nipples";
                case "male:tiger": return "male:tiger";
                case "male:body modification": return "male:body modification";
                case "male:dark sclera": return "male:dark sclera";
                case "male:centaur": return "male:centaur";
                case "male:merman": return "male:merman";
                case "male:smoking": return "male:smoking";
                case "male:wooden horse": return "male:wooden horse";
                case "male:machine": return "male:machine";
                case "male:scrotal lingerie": return "male:scrotal lingerie";
                case "male:paizuri": return "male:paizuri";
                case "male:raccoon boy": return "male:raccoon boy";
                case "male:shark boy": return "male:shark boy";
                case "male:birth": return "male:birth";
                case "male:tickling": return "male:tickling";
                case "male:mouse boy": return "male:mouse boy";
                case "male:electric shocks": return "male:electric shocks";
                case "male:balls expansion": return "male:balls expansion";
                case "male:emotionless sex": return "male:emotionless sex";
                case "male:nose hook": return "male:nose hook";
                case "male:lion": return "male:lion";
                case "male:ball sucking": return "male:ball sucking";
                case "male:nun": return "male:nun";
                case "male:pillory": return "male:pillory";
                case "male:cousin": return "male:cousin";
                case "male:shared senses": return "male:shared senses";
                case "male:sheep boy": return "male:sheep boy";
                case "male:farting": return "male:farting";
                case "male:ssbbm": return "male:ssbbm";
                case "male:blowjob face": return "male:blowjob face";
                case "male:kunoichi": return "male:kunoichi";
                case "male:low bestiality": return "male:low bestiality";
                case "male:inverted nipples": return "male:inverted nipples";
                case "male:assjob": return "male:assjob";
                case "male:swinging": return "male:swinging";
                case "male:blind": return "male:blind";
                case "male:randoseru": return "male:randoseru";
                case "male:trampling": return "male:trampling";
                case "male:forniphilia": return "male:forniphilia";
                case "male:fairy": return "male:fairy";
                case "male:grandfather": return "male:grandfather";
                case "male:absorption": return "male:absorption";
                case "male:heterochromia": return "male:heterochromia";
                case "male:unicorn": return "male:unicorn";
                case "male:slime boy": return "male:slime boy";
                case "male:anal birth": return "male:anal birth";
                case "male:rabbit": return "male:rabbit";
                case "male:speculum": return "male:speculum";
                case "male:sheep": return "male:sheep";
                case "male:growth": return "male:growth";
                case "male:petrification": return "male:petrification";
                case "male:prolapse": return "male:prolapse";
                case "male:animal on animal": return "male:animal on animal";
                case "male:slug": return "male:slug";
                case "male:phone sex": return "male:phone sex";
                case "male:horse cock": return "male:horse cock";
                case "male:gasmask": return "male:gasmask";
                case "male:hairy armpits": return "male:hairy armpits";
                case "male:all the way through": return "male:all the way through";
                case "male:pirate": return "male:pirate";
                case "male:wet clothes": return "male:wet clothes";
                case "male:pasties": return "male:pasties";
                case "male:elephant": return "male:elephant";
                case "male:multiple arms": return "male:multiple arms";
                case "male:spider": return "male:spider";
                case "male:eel": return "male:eel";
                case "male:kigurumi": return "male:kigurumi";
                case "male:milking": return "male:milking";
                case "male:goat": return "male:goat";
                case "male:fox": return "male:fox";
                case "male:body painting": return "male:body painting";
                case "male:brain fuck": return "male:brain fuck";
                case "male:donkey": return "male:donkey";
                case "male:tube": return "male:tube";
                case "male:fish": return "male:fish";
                case "male:turtle": return "male:turtle";
                case "male:pubic stubble": return "male:pubic stubble";
                case "male:weight gain": return "male:weight gain";
                case "male:shark": return "male:shark";
                case "male:penis birth": return "male:penis birth";
                case "male:crown": return "male:crown";
                case "male:clown": return "male:clown";
                case "male:saliva": return "male:saliva";
                case "male:crotch tattoo": return "male:crotch tattoo";
                case "male:armpit sex": return "male:armpit sex";
                case "male:monoeye": return "male:monoeye";
                case "male:vacbed": return "male:vacbed";
                case "male:syringe": return "male:syringe";
                case "male:zebra": return "male:zebra";
                case "male:big areolae": return "male:big areolae";
                case "male:witch": return "male:witch";
                case "male:dinosaur": return "male:dinosaur";
                case "male:nazi": return "male:nazi";
                case "male:balljob": return "male:balljob";
                case "male:twintails": return "male:twintails";
                case "male:harpy": return "male:harpy";
                case "male:insect boy": return "male:insect boy";
                case "male:mecha boy": return "male:mecha boy";
                case "male:worm": return "male:worm";
                case "male:panther": return "male:panther";
                case "male:ponytail": return "male:ponytail";
                case "male:bodystocking": return "male:bodystocking";
                case "male:living clothes": return "male:living clothes";
                case "male:triple penetration": return "male:triple penetration";
                case "male:plant boy": return "male:plant boy";
                case "male:pegasus": return "male:pegasus";
                case "male:squid boy": return "male:squid boy";
                case "male:dark nipples": return "male:dark nipples";
                case "male:hairjob": return "male:hairjob";
                case "male:beauty mark": return "male:beauty mark";
                case "male:muscle growth": return "male:muscle growth";
                case "male:gijinka": return "male:gijinka";
                case "male:triple anal": return "male:triple anal";
                case "male:mouse": return "male:mouse";
                case "male:ostrich": return "male:ostrich";
                case "male:stewardess": return "male:stewardess";
                case "male:tooth brushing": return "male:tooth brushing";
                case "male:adventitious penis": return "male:adventitious penis";
                case "male:whale": return "male:whale";
                case "male:doll joints": return "male:doll joints";
                case "male:snake boy": return "male:snake boy";
                case "male:dismantling": return "male:dismantling";
                case "male:clamp": return "male:clamp";
                case "male:animal on furry": return "male:animal on furry";
                case "male:navel fuck": return "male:navel fuck";
                case "male:steward": return "male:steward";
                case "male:nipple fuck": return "male:nipple fuck";
                case "male:cum bath": return "male:cum bath";
                case "male:tailjob": return "male:tailjob";
                case "male:stretching": return "male:stretching";
                case "male:rhinoceros": return "male:rhinoceros";
                case "male:foot insertion": return "male:foot insertion";
                case "male:alligator": return "male:alligator";
                case "male:maggot": return "male:maggot";
                case "male:closed eyes": return "male:closed eyes";
                case "male:bunny girl": return "male:bunny girl";
                case "male:lizard": return "male:lizard";
                case "male:squirrel boy": return "male:squirrel boy";
                case "male:crab": return "male:crab";
                case "male:pantyjob": return "male:pantyjob";
                case "male:table masturbation": return "male:table masturbation";
                case "male:pole dancing": return "male:pole dancing";
                case "male:glothic loli": return "male:glothic loli";
                case "male:tall guy": return "male:tall guy";
                case "male:plant guy": return "male:plant guy";
                case "male:tentecale": return "male:tentecale";
                case "male:eye penetration": return "male:eye penetration";
                case "male:golbin": return "male:golbin";
                case "male:camel": return "male:camel";
                case "male:harness": return "male:harness";
                case "male:anorexic": return "male:anorexic";
                case "male:dicknipples": return "male:dicknipples";
            }

            return eng_tag;
        }
    }
}
