/***

   Copyright (C) 2018-2019. dc-koromo. All Rights Reserved.
   
   Author: Koromo Copy Developer

***/

namespace Koromo_Copy.Component.Hitomi.Translate
{
    public static class KoreanSeries
    {
        public static string SeriesMap(string eng_series)
        {
            switch (eng_series)
            {
                case "touhou project": return "동방 프로젝트";
                case "kantai collection": return "함대 컬렉션";
                case "the idolmaster": return "아이돌 마스터";
                case "N/A": return "N/A";
                case "fate grand order": return "페이트 그랜드 오더";
                case "neon genesis evangelion": return "신세기 에반게리온";
                case "sailor moon": return "세일러문";
                case "mahou shoujo lyrical nanoha": return "마법소녀 리리컬 나노하";
                case "pokemon": return "포켓몬";
                case "to love-ru": return "To LOVE 트러블";
                case "love live": return "러브라이브";
                case "naruto": return "나루토";
                case "granblue fantasy": return "그랑블루 판타지";
                case "one piece": return "원피스";
                case "fate stay night": return "페이트 스테이 나이트";
                case "street fighter": return "스트리트 파이터";
                case "k-on": return "케이온";
                case "king of fighters": return "더 킹 오브 파이터즈";
                case "sword art online": return "소드 아트 온라인";
                case "dead or alive": return "Dead or Alive";
                case "puella magi madoka magica": return "마법소녀 마도카 마기카";
                case "ore no imouto ga konna ni kawaii wake ga nai": return "내 여동생이 이렇게 귀여울 리가 없어";
                case "girls und panzer": return "걸즈 & 판처";
                case "code geass": return "코드 기어스";
                case "the melancholy of haruhi suzumiya": return "스즈미야 하루히의 우울";
                case "bakemonogatari": return "바케모노가타리";
                case "free": return "프리!";
                case "final fantasy vii": return "파이널 판타지 7";
                case "bleach": return "블리치";
                case "toheart2": return "투 하트2";
                case "boku wa tomodachi ga sukunai": return "나는 친구가 적다";
                case "dragon quest iii": return "드래곤 퀘스트 3";
                case "ragnarok online": return "라그나로크 온라인";
                case "queens blade": return "퀸즈 블레이드";
                case "toaru kagaku no railgun": return "어떤 과학의 초전자포";
                case "vocaloid": return "보컬로이드";
                case "ah my goddess": return "오! 나의 여신님";
                case "cardcaptor sakura": return "카드캡터 채리";
                case "shingeki no kyojin": return "진격의 거인";
                case "monster hunter": return "몬스터 헌터";
                case "infinite stratos": return "인피니트 스트라토스";
                case "dragon ball z": return "드래곤볼 Z";
                case "smile precure": return "스마일 프리큐어!";
                case "darkstalkers": return "Darkstalkers";
                case "azur lane": return "벽람항로";
                case "gochuumon wa usagi desu ka": return "주문은 토끼입니까?";
                case "toaru majutsu no index": return "어떤 마술의 금서목록";
                case "samurai spirits": return "사무라이 스피리츠";
                case "mahou sensei negima": return "마법선생 네기마!";
                case "gundam seed destiny": return "기동전사 건담 SEED DESTINY";
                case "persona 4": return "페르소나 4";
                case "amagami": return "아마가미";
                case "zero no tsukaima": return "제로의 사역마";
                case "saki": return "사키";
                case "super robot wars": return "슈퍼 로봇 대전";
                case "dragon quest v": return "드래곤 퀘스트 V";
                case "strike witches": return "스트라이크 위치즈";
                case "touken ranbu": return "도검난무";
                case "kuroko no basuke": return "쿠로코의 농구";
                case "lucky star": return "러키☆스타";
                case "to heart": return "투 하트";
                case "ranma 12": return "란마 12";
                case "love plus": return "러브플러스";
                case "kanon": return "카논";
                case "ojamajo doremi": return "꼬마마법사 레미";
                case "dragon quest iv": return "드래곤 퀘스트 IV";
                case "kono subarashii sekai ni syukufuku o": return "이 멋진 세계에 축복을!";
                case "sakura taisen": return "사쿠라 대전";
                case "league of legends": return "리그 오브 레전드";
                case "danganronpa": return "단간론파";
                case "my hero academia": return "나의 히어로 아카데미아";
                case "love hina": return "러브히나";
                case "hayate no gotoku": return "하야테처럼!";
                case "tengen toppa gurren lagann": return "천원돌파 그렌라간";
                case "love live sunshine": return "러브라이브 션샤인";
                case "pretty cure": return "프리큐어";
                case "martian successor nadesico": return "기동전함 나데시코";
                case "yu-gi-oh": return "유희왕";
                case "dragon ball": return "드래곤볼";
                case "dragon quest": return "드래곤 퀘스트";
                case "tenchi muyo": return "천지무용!";
                case "chuunibyou demo koi ga shitai": return "중2병이라도 사랑이 하고 싶어!";
                case "guilty gear": return "길티 기어";
                case "rozen maiden": return "로젠 메이든";
                case "amagi brilliant park": return "아마기 브릴리언트 파크";
                case "gundam build fighters": return "건담 빌드 파이터즈";
                case "gundam seed": return "기동전사 건담";
                case "fullmetal alchemist": return "강철의 연금술사";
                case "fate kaleid liner prisma illya": return "Fate/kaleid liner 프리즈마☆이리야";
                case "haikyuu": return "하이큐!!";
                case "gundam 00": return "기동전사 건담 더블 오";
                case "soulcalibur": return "소울칼리버";
                case "sister princess": return "시스터 프린세스";
                case "dungeon ni deai o motomeru no wa machigatteiru darou ka": return "던전에서 만남을 추구하면 안 되는 걸까";
                case "ichigo 100": return "딸기 100%";
                case "kyoukai senjou no horizon": return "경계선상의 호라이즌";
                case "heartcatch precure": return "하트캐치 프리큐어!";
                case "macross frontier": return "마크로스 프론티어";
                case "suite precure": return "스위트 프리큐어♪";
                case "gundam build fighters try": return "건담 빌드 파이터즈 트라이";
                case "dokidoki precure": return "두근두근! 프리큐어";
                case "re zero kara hajimeru isekai seikatsu": return "Re:제로부터 시작하는 이세계 생활";
                case "fate zero": return "페이트 제로";
                case "yahari ore no seishun love come wa machigatteiru": return "역시 내 청춘 러브코메디는 잘못됐다.";
                case "fate hollow ataraxia": return "Fate/hollow ataraxia";
                case "shokugeki no soma": return "식극의 소마";
                case "tsukihime": return "월희";
                case "senran kagura": return "섬란 카구라";
                case "fairy tail": return "페어리 테일";
                case "final fantasy xi": return "파이널 판타지 11";
                case "axis powers hetalia": return "헤타리아 Axis Powers";
                case "urusei yatsura": return "시끌별 녀석들";
                case "working": return "WORKING!!";
                case "detective conan": return "명탐정 코난";
                case "resident evil": return "레지던트 이블";
                case "nisekoi": return "니세코이";
                case "dog days": return "도그 데이즈";
                case "seiken densetsu 3": return "성검전설 3";
                case "higurashi no naku koro ni": return "쓰르라미 울 적에";
                case "blazblue": return "블레이블루";
                case "shinrabansho": return "신라만상";
                case "persona 3": return "페르소나 3";
                case "steinsgate": return "슈타인즈 게이트";
                case "ano hi mita hana no namae wo bokutachi wa mada shiranai": return "그날 본 꽃의 이름을 우리는 아직 모른다";
                case "onegai teacher": return "플리즈 티처";
                case "yotsubato": return "요츠바랑!";
                case "kemono friends": return "케모노 프렌즈";
                case "eromanga sensei": return "에로망가 선생";
                case "azumanga daioh": return "아즈망가 대왕";
                case "dream c club": return "Dream Club";
                case "gintama": return "은혼";
                case "school rumble": return "스쿨럼블";
                case "inazuma eleven": return "이나즈마 일레븐";
                case "dynasty warriors": return "진·삼국무쌍";
                case "mitsudomoe": return "쓰리몬";
                case "keroro gunsou": return "개구리 중사 케로로";
                case "hyperdimension neptunia": return "초차원게임 넵튠";
                case "go princess precure": return "Go! 프린세스 프리큐어";
                case "pripara": return "프리파라";
                case "fresh precure": return "프레시 프리큐어!";
                case "toradora": return "토라도라!";
                case "highschool of the dead": return "학원묵시록";
                case "space battleship yamato": return "우주전함 야마토";
                case "gundam": return "건담";
                case "tokimeki memorial": return "두근두근 메모리얼";
                case "clannad": return "클라나드";
                case "yowamushi pedal": return "겁쟁이 페달";
                case "my little pony friendship is magic": return "마이 리틀 포니: 우정은 마법";
                case "final fantasy": return "파이널 판타지";
                case "dagashi kashi": return "다가시카시";
                case "aikatsu": return "아이 엠 스타!";
                case "maria-sama ga miteru": return "마리아님이 보고계셔";
                case "ikkitousen": return "일기당천";
                case "tiger and bunny": return "TIGER & BUNNY";
                case "sennen sensou aigis": return "천년전쟁 아이기스";
                case "baka to test to shoukanjuu": return "바보와 시험과 소환수";
                case "hyouka": return "빙과";
                case "tekken": return "철권";
                case "cardfight vanguard": return "카드파이트!! 뱅가드";
                case "slayers": return "슬레이어즈";
                case "super sonico": return "슈퍼 소니코";
                case "etrian odyssey": return "Etrian Odyssey";
                case "the legend of zelda": return "젤다의 전설";
                case "tales of the abyss": return "테일즈 오브 어비스";
                case "kannagi": return "칸나기";
                case "dragon quest viii": return "드래곤 퀘스트 8";
                case "kill la kill": return "킬라킬";
                case "magic knight rayearth": return "마법기사 레이어스";
                case "persona 5": return "페르소나 5";
                case "fire emblem": return "파이어 엠블렘";
                case "digimon": return "디지몬";
                case "galaxy angel": return "갤럭시 엔젤";
                case "ao no exorcist": return "청의 엑소시스트";
                case "yes precure 5": return "Yes! 프리큐어5";
                case "spice and wolf": return "늑대와 향신료";
                case "one punch man": return "원펀맨";
                case "saenai heroine no sodatekata": return "시원찮은 그녀를 위한 육성방법";
                case "yu-gi-oh zexal": return "유희왕 ZEXAL";
                case "dirty pair": return "더티페어";
                case "mai-hime": return "마이히메";
                case "magi the labyrinth of magic": return "마기";
                case "genshiken": return "현시연";
                case "fire emblem if": return "파이어 엠블렘";
                case "accel world": return "액셀 월드";
                case "happinesscharge precure": return "해피니스 차지 프리큐어!";
                case "god eater": return "갓 이터";
                case "yu-gi-oh arc-v": return "유희왕 ARC-V";
                case "black lagoon": return "블랙 라군";
                case "disgaea": return "마계전기 디스가이아";
                //case "the legend of heroes": return "The Legend of Heroes";
                case "jojos bizarre adventure": return "죠죠의 기묘한 모험";
                case "chobits": return "쵸비츠";
                case "fushigi no umi no nadia": return "신비한 바다의 나디아";
                case "fushigiboshi no futagohime": return "신비한 별의 쌍둥이 공주";
                case "uta no prince-sama": return "노래의☆왕자님♪"; // 노래하는 왕자님
                case "inuyasha": return "이누야샤";
                case "kimikiss": return "키미키스";
                case "angel beats": return "엔젤 비트";
                //case "dragons crown": return "Dragon's Crown";
                case "comic party": return "코믹 파티";
                case "katekyo hitman reborn": return "가정교사 히트맨 REBORN!";
                case "highschool dxd": return "하이스쿨 D×D";
                case "digimon adventure": return "디지몬 어드벤처";
                case "quiz magic academy": return "퀴즈 매직 아카데미";
                case "yuruyuri": return "유루유리";
                case "sora no otoshimono": return "하늘의 유실물";
                case "kizuato": return "키즈아토";
                case "durarara": return "듀라라라!!";
                case "ookiku furikabutte": return "크게 휘두르며";
                case "dragon quest xi": return "드래곤 퀘스트 11";
                //case "rival schools": return "Rival Schools";
                case "kodomo no jikan": return "아이들의 시간";
                case "sekirei": return "세키레이";
                case "hunter x hunter": return "헌터 × 헌터";
                case "xenosaga": return "제노사가";
                case "bakuman": return "바쿠만";
                case "panty and stocking with garterbelt": return "팬티 & 스타킹 with 가터벨트";
                case "final fantasy xii": return "파이널 판타지 12";
                case "arcana heart": return "아르카나 하트";
                case "final fantasy tactics": return "Final Fantasy Tactics";
                //case "flower knight girl": return "FLOWER KNIGHT GIRL";
                case "valkyria chronicles": return "전장의 발큐리아";
                //case "summon night": return "Summon Night";
                case "tales of vesperia": return "테일즈 오브 베스페리아";
                case "ensemble stars": return "앙상블 스타즈!";
                case "oshiete galko-chan": return "가르쳐줘! 갸루코쨩";
                case "mahouka koukou no rettousei": return "마법과고교의 열등생";
                case "fatal fury": return "아랑전설";
                case "koihime musou": return "연희무쌍";
                case "minami-ke": return "미나미가";
                case "gunparade march": return "건퍼레이드 오케스트라";
                case "doraemon": return "도라에몽";
                case "shakugan no shana": return "작안의 샤나";
                case "alice in wonderland": return "이상한 나라의 앨리스";
                case "date a live": return "데이트 어 라이브";
                //case "utawarerumono": return "utawarerumono";
                case "megaman": return "록맨";
                case "super mario brothers": return "슈퍼 마리오브라더스";
                //case "darker than black": return "DARKER THAN BLACK";
                case "maison ikkoku": return "메종일각";
                case "record of lodoss war": return "로도스도 전기";
                case "summer wars": return "썸머 워즈";
                case "ano natsu de matteru": return "그 여름에서 기다릴게";
                case "fire emblem awakening": return "파이어 엠블렘 어웨이킹";
                case "saint seiya": return "세인트 세이야";
                case "final fantasy x": return "파이널 판타지 10";
                case "twin angels": return "음수성전";
                case "pretty sammy": return "마법 소녀 프리티 사미";
                case "uchuu no stellvia": return "우주의 스텔비아";
                case "mobile suit gundam tekketsu no orphans": return "기동전사 건담 철혈의 오펀스";
                case "tokyo ghoul": return "도쿄 구울";
                // case "is": return "is"; ? 인피니트 스트라토드
                case "the world god only knows": return "신만이 아는 세계";
                //case "tales of xillia": return "tales of xillia";
                case "mobile suit gundam": return "기동전사 건담";
                case "senki zesshou symphogear": return "전희절창 심포기어";
                //case "muv-luv": return "muv-luv";
                //case "taimanin asagi": return "taimanin asagi";
                case "hentai ouji to warawanai neko": return "변태왕자와 웃지 않는 고양이";
                case "puzzle and dragons": return "퍼즐앤드래곤";
                case "final fantasy x-2": return "파이널 판타지 X-2";
                case "ro-kyu-bu": return "로큐브!";
                case "mai-otome": return "마이 오토메";
                case "eureka 7": return "유레카 7";
                case "kochikame": return "여기는 잘나가는 파출소";
                case "hataraku maou-sama": return "알바 뛰는 마왕님!";
                case "hikaru no go": return "히카루의 바둑";
                case "yuri on ice": return "유리!!! on ICE";
                case "final fight": return "파이널 파이트";
                case "historys strongest disciple kenichi": return "사상최강의 제자 켄이치";
                case "kobayashi-san-chi no maid dragon": return "코바야시네 메이드래곤";
                //case "super black jack": return "super black jack";
                //case "super real mahjong": return "super real mahjong";
                case "medaka box": return "메다카 박스";
                case "gegege no kitarou": return "게게게의 기타로";
                case "maho girls precure": return "마법사 프리큐어!";
                case "kirakira precure a la mode": return "키라키라☆프리큐어 아라모드";
                case "chousoku henkei gyrozetter": return "초속변형 자이로제타";
                case "sengoku basara": return "전국 바사라";
                case "zettai junpaku mahou shoujo": return "절대순백 ♡ 마법소녀";
                case "sentimental graffiti": return "센티멘탈 그래피티";
                case "metroid": return "메트로이드";
                case "cutey honey": return "큐티 하니";
                case "shinryaku ika musume": return "침략! 오징어 소녀";
                case "ichigo mashimaro": return "딸기 마시마로";
                case "final fantasy v": return "파이널 판타지 10";
                case "di gi charat": return "디지캐럿";
                case "gaogaigar": return "용자왕 가오가이가";
                case "full metal panic": return "풀 메탈 패닉!";
                case "final fantasy xiii": return "파이널 판타지 13";
                case "shirobako": return "시로바코";
                //case "viper": return "viper";
                case "beatmania": return "비트매니아";
                case "sayonara zetsubou sensei": return "안녕, 절망선생";
                case "hanasaku iroha": return "꽃이 피는 첫걸음";
                case "ace attorney": return "역전재판";
                case "rance": return "란스";
                case "maoyuu maou yuusha": return "마오유우 마왕용사";
                //case "mahou shoujo ai": return "mahou shoujo ai";
                //case "phantasy star online 2": return "phantasy star online 2";
                case "lotte no omocha": return "롯테의 장난감!";
                case "aquarion evol": return "아쿠에리온 EVOL";
                case "final fantasy vi": return "파이널 판타지 11";
                case "nier automata": return "니어:오토마타";
                case "haiyore nyaruko-san": return "기어와라! 냐루코 양";
                case "tera": return "테라";
                case "kekkai sensen": return "혈계전선";
                case "gundam zz": return "기동전사 건담 ZZ";
                case "new game": return "NEW GAME!";
                case "witchblade": return "위치블레이드";
                case "harry potter": return "해리 포터";
                case "battle athletes": return "파이팅! 대운동회";
                case "daiya no ace": return "다이아몬드 A";
                case "overwatch": return "오버워치";
                case "final fantasy iv": return "파이널 판타지 4";
                case "inu x boku ss": return "이누×보쿠SS";
                case "zettai karen children": return "절대 가련 칠드런";
                case "dragon quest dai no daibouken": return "타이의 대모험";
                case "tantei opera milky holmes": return "탐정 오페라 밀키홈즈";
                case "d.gray-man": return "디 그레이맨";
                case "fun fun pharmacy": return "신비한 마법 판판 파마시 ";
                //case "k": return "k";
                case "death note": return "데스노트";
                case "rurouni kenshin": return "바람의 검심";
                case "nanatsu no taizai": return "일곱 개의 대죄";
                case "youre under arrest": return "체포하라";
                case "bayonetta": return "베요네타";
                case "undertale": return "언더테일";
                case "suisei no gargantia": return "취성의 가르간티아";
                case "sonic the hedgehog": return "소닉 더 헤지호그";
                case "air": return "에어";
                case "non non biyori": return "논논비요리";
                case "prison school": return "감옥학원";
                case "onegai my melody": return "부탁해! 마이멜로디";
                case "hell teacher nube": return "지옥선생 누베";
                case "taimanin yukikaze": return "대마인 유키카제";
                case "ultraman": return "울트라맨";
                case "rumble roses": return "럼블로즈";
                case "soul eater": return "소울 이터";
                case "splatoon": return "스플래툰";
                case "final fantasy ix": return "파이널 판타지 9";
                case "bakusou kyoudai lets and go": return "우리는 챔피언";
                case "little busters": return "리틀 버스터즈";
                case "g gundam": return "기동무투전 G 건담";
                case "girls frontline": return "소녀전선";
                case "da capo": return "다카포";
                case "boruto": return "보루토";
                //case "black cat": return "black cat";
                case "akazukin cha cha": return "빨간 망토 차차";
                case "ghost in the shell": return "공각기동대";
                case "revolutionary girl utena": return "소녀혁명 우테나";
                case "hibike euphonium": return "울려라! 유포니엄";
                //case "fire emblem mystery of the emblem": return "fire emblem mystery of the emblem";
                case "monster girl quest": return "몬무스 퀘스트";
                case "fate extra": return "Fate/EXTRA";
                case "osomatsu-san": return "오소마츠상";
                case "tamako market": return "타마코 마켓";
                case "its not my fault that im not popular": return "내가 인기 없는 건 아무리 생각해도 너희들 탓이야!";
                case "busou renkin": return "무장연금";
                case "battle spirits": return "배틀 스피리츠";
                case "xenogears": return "제노기어스";
                case "umineko no naku koro ni": return "괭이갈매기 울 적에";
                case "vividred operation": return "비비드레드 오퍼레이션";
                case "rosario vampire": return "로자리오와 뱀파이어";
                case "pani poni dash": return "파니포니 대쉬";
                case "mabinogi": return "마비노기";
                case "turn a gundam": return "턴에이 건담";
                case "puyo puyo": return "뿌요뿌요";
                case "koutetsujou no kabaneri": return "갑철성의 카바네리";
                case "onegai twins": return "오네가이 트윈즈";
                case "zoids genesis": return "조이드 제네시스";
                case "denpa onna to seishun otoko": return "전파녀와 청춘남";
                case "ghost sweeper mikami": return "고스트 스위퍼 미카미";
                case "hoozuki no reitetsu": return "호오즈키의 냉철";
                case "tokyo mew mew": return "베리베리 뮤우뮤우";
                case "tales of symphonia": return "테일즈 오브 심포니아";
                case "bamboo blade": return "뱀부 블레이드";
                case "pangya": return "팡야";
                case "kimi no na wa.": return "너의 이름은.";
                case "getsuyoubi no tawawa": return "월요일의 타와와";
                case "he is my master": return "나의 주인님";
                case "powerpuff girls z": return "파워퍼프걸Z";
                case "hidamari sketch": return "히다마리 스케치";
                //case "magical emi": return "magical emi";
                case "voiceroid": return "보이스로이드";
                case "mahou tsukai no yoru": return "마법사의 밤";
                case "pia carrot": return "웰컴 투 피아 캐럿";
                //case "mega man legends": return "mega man legends";
                case "final fantasy viii": return "파이널 판타지 8";
                case "dragon quest ii": return "드레곤 퀘스트 2";
                case "onmyou taisenki": return "음양대전기";
                //case "os-tan": return "os-tan";
                case "elsword": return "엘소드";
                case "creamy mami": return "천사소녀 새롬이";
                case "read or die": return "R.O.D";
                case "zootopia": return "주토피아";
                case "world trigger": return "월드 트리거";
                case "sekai seifuku bouryaku no zvezda": return "세계정복 ~모략의 즈베즈다~";
                case "digimon tamers": return "디지몬 테이머즈";
                //case "aria": return "aria";
                case "kimagure orange road": return "변덕스러운 오렌지로드";
                case "yu-gi-oh 5ds": return "유희왕 5D's";
                case "himouto umaru-chan": return "건어물 여동생! 우마루짱";
                case "tales of graces": return "테일즈 오브 그레이세스";
                case "dragon ball super": return "드래곤볼 슈퍼";
                case "aldnoah.zero": return "알드노아. 제로";
                case "eyeshield 21": return "아이실드 21";
                case "ansatsu kyoushitsu": return "암살교실";
                case "dennou coil": return "전뇌 코일";
                case "darling in the franxx": return "달링 인 더 프랑키스";
                case "da capo ii": return "다카포 2";
                case "shaman king": return "샤먼킹";
                case "berserk": return "베르세르크";
                case "tokyo 7th sisters": return "Tokyo 7th 시스터즈";
                case "witch craft works": return "위치 크래프트 워크스";
                case "lupin iii": return "루팡 3세";
                case "youkai watch": return "요괴워치";
                //case "dragonaut": return "dragonaut";
                case "saber marionette": return "세이버 마리오넷";
                case "nichijou": return "일상";
                case "myriad colors phantom world": return "무채한의 팬텀 월드";
                case "little red riding hood": return "빨간 두건";
                case "arpeggio of blue steel": return "푸른 강철의 아르페지오";
                case "shin megami tensei": return "진 여신전생";
                case "zeta gundam": return "Z 건담";
                case "ore twintail ni narimasu.": return "저, 트윈 테일이 됩니다";
                case "dungeon fighter online": return "던전앤파이터";
                case "cosmic baton girl comet-san": return "Cosmic Baton Girl 코메트상☆";
                case "overlord": return "오버로드";
                case "gate - jietai kano chi nite kaku tatakaeri": return "게이트 - 자위대. 그의 땅에서, 이처럼 싸우며";
                case "black butler": return "흑집사";
                case "kiddy grade": return "키디 그레이드";
                case "gad guard": return "가드 가드";
                case "prince of tennis": return "테니스의 왕자";
                case "zoids": return "조이드";
                case "muv-luv alternative total eclipse": return "마브러브 얼터너티브 토탈 이클립스 ";
                case "kiniro mosaic": return "금빛 모자이크";
                case "nurarihyon no mago": return "누라리횬의 손자";
                case "galaxy express 999": return "은하철도 999";
                case "yu-gi-oh gx": return "유희왕 GX";
                case "dramatical murder": return "드라마티컬 머더";
                case "angelic layer": return "기동천사 엔젤릭 레이어";
                case "oda nobuna no yabou": return "오다 노부나의 야망";
                case "expelled from paradise": return "낙원추방";
                //case "endless frontier": return "endless frontier";
                case "samurai warriors": return "전국무쌍";
                case "mirai nikki": return "미래일기";
                case "no game no life": return "노 게임·노 라이프";
                case "7th dragon": return "세븐스 드래곤";
                case "mayo chiki": return "마요치키!";
                //case "gundam wing": return "신기동전기 건담 W";
                case "kimi ga nozomu eien": return "그대가 바라는 영원";
                case "made in abyss": return "메이드 인 어비스";
                case "hand maid may": return "핸드 메이드 메이";
                case "princess lover": return "프린세스 러버";
                case "princess crown": return "프린세스 크라운";
                //case "viper rsr": return "viper rsr";
                //case "with you": return "with you";
                case "princess resurrection": return "괴물왕녀";
                case "gabriel dropout": return "가브릴 드롭아웃";
                case "beat blades haruka": return "초앙전인 하루카";
                case "papa no iu koto wo kikinasai": return "아빠 말 좀 들어라!";
                case "final fantasy xv": return "파이널 판타지 15";
                case "maria holic": return "마리아†홀릭";
                case "ashita no nadja": return "내일의 나쟈";
                case "macross 7": return "마크로스7";
                //case "bastard": return "bastard";
                case "gakkou no kaidan": return "학교괴담";
                case "fate apocrypha": return "Fate/Apocrypha";
                case "inazuma eleven go": return "이나즈마 일레븐 GO";
                case "tokyo afterschool summoners": return "도쿄 방과후 서모너즈";
                case "hellsing": return "헬싱";
                case "anyamaru tantei kiruminzoo": return "쥬로링 동물탐정";
                case "fantasy earth zero": return "판타지 어스: 제로";
                case "giant robo": return "자이언트 로보";
                case "virtua fighter": return "버추어 파이터";
                case "monster musume no iru nichijou": return "몬스터 아가씨가 있는 일상";
                case "cats eye": return "캐츠 아이";
                case "another": return "어나더";
                case "ookami-san to shichinin no nakama-tachi": return "오오카미 씨와 7명의 동료들";
                case "moyashimon": return "모야시몬";
                //case "betterman": return "betterman";
                //case "major": return "major";
                case "danball senki": return "골판지전기";
                case "mahoromatic": return "마호로매틱";
                case "kino no tabi": return "키노의 여행";
                case "gundam unicorn": return "기동전사 건담 UC";
                case "kanokon": return "카노콘";
                case "log horizon": return "로그 호라이즌";
                case "mahou no juujin foxy rena": return "마법의 십자가 · 호쿠 레이나";
                case "gantz": return "간츠";
                case "tower of druaga": return "드루아가의 탑";
                case "variable geo": return "베리어블 지오";
                case "cowboy bebop": return "카우보이 비밥";
                case "seraph of the end": return "종말의 세라프";
                case "phantasy star online": return "판타지 스타 온라인";
                case "white album": return "화이트 앨범";
                case "x-men": return "엑스맨";
                case "maji de watashi ni koi shinasai": return "진심으로 날 사랑해라!!";
                case "occult academy": return "세기말 오컬트 학원";
                case "seto no hanayome": return "세토의 신부";
                case "jormungand": return "요르문간드";
                case "final fantasy xiv": return "파이널 판타지 14";
                case "hitsugi no chaika": return "관희 챠이카";
                case "world masterpiece theater": return "세계명작극장";
                case "gj-bu": return "GJ부";
                case "sono hanabira ni kuchizuke o": return "그 꽃잎에 입맞춤을";
                case "inyouchuu": return "음요충";
                case "kindaichi shounen no jikenbo": return "소년탐정 김전일";
                //case "beat angel escalayer": return "beat angel escalayer";
                case "gunslinger girl": return "건슬링거 걸";
                case "kampfer": return "캠퍼";
                case "black bullet": return "블랙 불릿";
                case "nausicaa of the valley of the wind": return "바람계곡의 나우시카";
                case "mamotte shugogetten": return "수호월천";
                case "kaitou tenshi twin angel": return "쾌도천사 트윈 엔젤";
                case "utawarerumono itsuwari no kamen": return "칭송을 받는 자: 거짓의 가면";
                case "ai yori aoshi": return "쪽빛보다 푸르게";
                case "city hunter": return "시티헌터";
                case "devil may cry": return "데빌 메이 크라이";
                //case "mamono musume zukan": return "mamono musume zukan";
                case "digimon frontier": return "디지몬 프론티어";
                case "medabots": return "메다로트";
                case "tales of zestiria": return "테일즈 오브 제스티리아";
                case "yuyushiki": return "유유시키";
                case "tobe isami": return "날아라 이사미";
                case "sora wo kakeru shoujo": return "우주를 달리는 소녀";
                case "ar tonelico": return "아르 토네리코";
                case "super doll licca-chan": return "인형공주 리카";
                case "kid icarus": return "키드 이카루스";
                case "blend s": return "블렌드·S";
                case "pretty rhythm": return "프리티 리듬";
                case "victory gundam": return "기동전사 V 건담";
                //case "otogi-jushi akazukin": return "otogi-jushi akazukin";
                case "gear fighter dendoh": return "기어전사 덴도우";
                case "valkyrie profile": return "발키리 프로파일";
                case "minky momo": return "요술공주 밍키";
                case "little witch academia": return "리틀 위치 아카데미아";
                case "star gladiator": return "스타 글래디에이터";
                case "big hero 6": return "빅 히어로";
                case "final fantasy unlimited": return "파이널 판타지 언리미티드";
                case "phantasy star": return "판타지 스타";
                case "psycho-pass": return "사이코 패스";
                case "el hazard": return "엘하자드";
                case "wedding peach": return "웨딩피치";
                case "lord of lords ryu knight": return "패왕대계 류나이트";
                case "ouran high school host club": return "오란고교 호스트부";
                case "walkure romanze": return "왈큐레 로만체";
                case "solatorobo": return "소라토로보";
                case "dragon ball gt": return "드래곤볼 GT";
                case "valkyrie no bouken": return "왈큐레의 모험";
                case "claymore": return "클레이모어";
                case "the vision of escaflowne": return "천공의 에스카플로네";
                case "saint tail": return "천사소녀 네티";
                case "sonic soldier borgman": return "초음전사 보그맨";
                case "fruits basket": return "후르츠 바스켓";
                case "cream lemon": return "크림 레몬";
                case "gunbuster": return "건버스터";
                case "hacka doll": return "해커돌";
                case "dragon quest vi": return "드래곤 퀘스트 6";
                case "wizard of oz": return "오즈의 마법사";
                case "hatsukoi limited": return "첫사랑 한정";
                //case "demonbane": return "demonbane";
                case "moetan": return "모에땅";
                case "night shift nurses": return "야근병동";
                case "yuru camp": return "유루캠프△";
                case "noir": return "느와르";
                case "gatchaman crowds": return "갓챠맨 크라우즈";
                //case "houkago play": return "houkago play";
                case "mahoujin guru guru": return "마법진 구루구루";
                case "akihabara dennou gumi": return "아키하바라 전뇌조";
                case "maken-ki": return "마켄키";
                case "ben-to": return "도시락 전쟁";
                case "majin tantei nougami neuro": return "마인탐정 네우로";
                case "tales of": return "테일즈 시리즈";
                case "outbreak company": return "아웃브레이크 컴퍼니";
                case "atelier totori": return "토토리의 아틀리에";
                case "megaman battle network": return "메가맨 배틀 네트워크";
                case "gundam age": return "기동전사건담 에이지";
                //case "okusan": return "okusan";
                case "popn music": return "팝픈뮤직";
                case "dragon quest x": return "드래곤 퀘스트 10";
                case "girl friend beta": return "걸 프렌드 (베타)";
                case "yatterman": return "이겨라 승리호";
                case "kaleido star": return "카레이도 스타";
                case "skies of arcadia": return "스카이즈 오브 알카디아";
                case "black rock shooter": return "블랙 락 슈터";
                case "yakitate japan": return "따끈따끈 베이커리";
                //case "ecoko": return "ecoko";
                case "nagi no asukara": return "잔잔한 내일로부터 ";
                //case "akebi no mi": return "akebi no mi";
                case "freezing": return "프리징";
                case "gakkou gurashi": return "학교생활!";
                case "sengoku otome": return "전국 소녀";
                case "shugo chara": return "캐릭캐릭 체인지";
                //case "mugen senshi valis": return "mugen senshi valis";
                case "rakudai kishi no cavalry": return "낙제기사의 영웅담";
                case "nyan koi": return "냥코이!";
                case "show by rock": return "쇼 바이 락!!";
                case "renkin san-kyuu magical pokaan": return "연금3급 매지컬 포카앙";
                case "kamen rider": return "가면 라이더";
                case "nurse witch komugi": return "너스위치 코무기짱";
                case "strike the blood": return "스트라이크 더 블러드";
                case "batman": return "배트맨";
                case "asobi ni iku yo": return "놀러 갈게!";
                case "kangoku senkan": return "감옥전함";
                case "warriors orochi": return "무쌍 오로치";
                case "ryuuou no oshigoto": return "용왕이 하는 일!";
                case "odin sphere": return "오딘 스피어";
                case "busou shinki": return "무장신희";
                case "agent aika": return "에이젼트 아이카";
                case "yoru no yatterman": return "밤의 얏타맨";
                case "kuroinu kedakaki seijo wa hakudaku ni somaru": return "흑수(크로이누) ~고상한 성녀는 백탁에 물들다~";
                case "sakurasou no pet na kanojo": return "사쿠라장의 애완그녀";
                case "athena": return "아테나";
                //case "star ocean 2": return "star ocean 2";
                case "star driver": return "스타 드라이버";
                case "toriko": return "토리코";
                case "kaichou wa maid-sama": return "회장님은 메이드 사마";
                case "kare kano": return "kare kano";
                case "a channel": return "a channel";
                case "mazinger z": return "mazinger z";
                case "yondemasuyo azazel-san": return "yondemasuyo azazel-san";
                case "animal crossing": return "animal crossing";
                case "seiken densetsu": return "seiken densetsu";
                case "mawaru penguindrum": return "mawaru penguindrum";
                case "lightning warrior raidy": return "lightning warrior raidy";
                case "reco love": return "reco love";
                case "sangokushi taisen": return "sangokushi taisen";
                case "fire emblem rekka no ken": return "fire emblem rekka no ken";
                case "dragon quest ix": return "dragon quest ix";
                case "macross delta": return "macross delta";
                case "yu yu hakusho": return "yu yu hakusho";
                case "sket dance": return "sket dance";
                case "2x2 shinobuden": return "2x2 shinobuden";
                case "wingman": return "wingman";
                case "brave witches": return "brave witches";
                case "yu-gi-oh vrains": return "yu-gi-oh vrains";
                case "shuffle": return "shuffle";
                case "viper gts": return "viper gts";
                case "demons souls": return "demons souls";
                case "d-frag": return "d-frag";
                case "avengers": return "avengers";
                case "phantasy star portable 2": return "phantasy star portable 2";
                case "cyberbots": return "cyberbots";
                case "yama no susume": return "yama no susume";
                case "kara no kyoukai": return "kara no kyoukai";
                case "gravitation": return "gravitation";
                case "kamikaze kaitou jeanne": return "kamikaze kaitou jeanne";
                case "school days": return "school days";
                case "kuma miko": return "kuma miko";
                case "karakai jouzu no takagi-san": return "karakai jouzu no takagi-san";
                case "sengoku collection": return "sengoku collection";
                case "vandread": return "vandread";
                case "jigoku shoujo": return "jigoku shoujo";
                case "akame ga kill": return "akame ga kill";
                case "star fox": return "star fox";
                case "doki doki majo shinpan": return "doki doki majo shinpan";
                case "shironeko project": return "shironeko project";
                case "gundam 0083": return "gundam 0083";
                case "yuuki yuuna wa yuusha de aru": return "yuuki yuuna wa yuusha de aru";
                case "kingdom hearts": return "kingdom hearts";
                case "mega man star force": return "mega man star force";
                case "nintama rantarou": return "nintama rantarou";
                case "hime-chans ribbon": return "hime-chans ribbon";
                case "nurse angel ririka sos": return "nurse angel ririka sos";
                case "tales of phantasia": return "tales of phantasia";
                case "suigetsu": return "suigetsu";
                case "rinne no lagrange": return "rinne no lagrange";
                case "art of fighting": return "art of fighting";
                case "esper mami": return "esper mami";
                case "cyborg 009": return "cyborg 009";
                case "seikon no qwaser": return "seikon no qwaser";
                case "gekkan shoujo nozaki-kun": return "gekkan shoujo nozaki-kun";
                case "demi-chan wa kataritai": return "demi-chan wa kataritai";
                case "overman king gainer": return "overman king gainer";
                case "kamichu": return "kamichu";
                case "devil survivor 2": return "devil survivor 2";
                case "shinmai maou no testament": return "shinmai maou no testament";
                case "yosuga no sora": return "yosuga no sora";
                case "corrector yui": return "corrector yui";
                case "fancy lala": return "fancy lala";
                case "skullgirls": return "skullgirls";
                case "mahou tsukai tai": return "mahou tsukai tai";
                case "ange vierge": return "ange vierge";
                case "seitokai yakuindomo": return "seitokai yakuindomo";
                case "guilty crown": return "guilty crown";
                case "warship girls": return "warship girls";
                case "ng knight lamune and 40": return "ng knight lamune and 40";
                case "kore wa zombie desu ka": return "kore wa zombie desu ka";
                case "twinbee": return "twinbee";
                case "hamtaro": return "hamtaro";
                case "outlaw star": return "outlaw star";
                case "fujiyama-san wa shishunki": return "fujiyama-san wa shishunki";
                case "jubei-chan": return "jubei-chan";
                case "kagerou project": return "kagerou project";
                case "patlabor": return "patlabor";
                case "kasumin": return "kasumin";
                case "dorei to no seikatsu": return "dorei to no seikatsu";
                case "tsuyokiss": return "tsuyokiss";
                case "valkyria chronicles 3": return "valkyria chronicles 3";
                case "servant x service": return "servant x service";
                case "kyoukai no kanata": return "kyoukai no kanata";
                case "yoake mae yori ruriiro na": return "yoake mae yori ruriiro na";
                case "hai to gensou no grimgar": return "hai to gensou no grimgar";
                case "phantasy star universe": return "phantasy star universe";
                case "katanagatari": return "katanagatari";
                case "the sacred blacksmith": return "the sacred blacksmith";
                case "brave police j-decker": return "brave police j-decker";
                case "charlotte": return "charlotte";
                case "zatch bell": return "zatch bell";
                case "togainu no chi": return "togainu no chi";
                case "tenchi muyo gxp": return "tenchi muyo gxp";
                case "jewelpet tinkle": return "jewelpet tinkle";
                case "frame arms girl": return "frame arms girl";
                case "gravion": return "gravion";
                case "xenoblade chronicles 2": return "xenoblade chronicles 2";
                case "hakuouki": return "hakuouki";
                case "dream hunter rem": return "dream hunter rem";
                case "da capo iii": return "da capo iii";
                case "the onechanbara": return "the onechanbara";
                case "fatal frame": return "fatal frame";
                case "real drive": return "real drive";
                case "takamare takamaru": return "takamare takamaru";
                case "jewelpet": return "jewelpet";
                case "mouretsu pirates": return "mouretsu pirates";
                case "gosick": return "gosick";
                case "koe no katachi": return "koe no katachi";
                case "dr. slump": return "dr. slump";
                case "silent hill": return "silent hill";
                case "drifters": return "drifters";
                case "ga-rei": return "ga-rei";
                case "kakyuusei": return "kakyuusei";
                case "makai tenshi jibril": return "makai tenshi jibril";
                case "future card buddyfight": return "future card buddyfight";
                case "kaiten mutenmaru": return "kaiten mutenmaru";
                case "occultic nine": return "occultic nine";
                case "otome wa boku ni koishiteru": return "otome wa boku ni koishiteru";
                case "fist of the north star": return "fist of the north star";
                case "pretty cure splash star": return "pretty cure splash star";
                case "dungeon meshi": return "dungeon meshi";
                case "ane doki": return "ane doki";
                case "whistle": return "whistle";
                case "blue dragon": return "blue dragon";
                case "flcl": return "flcl";
                case "tsukuyomi moon phase": return "tsukuyomi moon phase";
                case "star ocean 3": return "star ocean 3";
                case "rewrite": return "rewrite";
                case "valvrave the liberator": return "valvrave the liberator";
                case "youjo senki": return "youjo senki";
                case "rune factory": return "rune factory";
                case "beelzebub": return "beelzebub";
                case "journey to the west": return "journey to the west";
                case "kuttsukiboshi": return "kuttsukiboshi";
                case "oboro muramasa": return "oboro muramasa";
                case "sisters natsu no saigo no hi": return "sisters natsu no saigo no hi";
                case "boku dake ga inai machi": return "boku dake ga inai machi";
                case "mon colle knights": return "mon colle knights";
                case "words worth": return "words worth";
                case "ane naru mono": return "ane naru mono";
                case "shinmai fukei kiruko-san": return "shinmai fukei kiruko-san";
                case "getter robo": return "getter robo";
                case "heroman": return "heroman";
                case "wrestle angels": return "wrestle angels";
                case "kamisama dolls": return "kamisama dolls";
                case "la pucelle": return "la pucelle";
                case "gundam x": return "gundam x";
                case "tari tari": return "tari tari";
                case "crayon shin-chan": return "crayon shin-chan";
                case "zeroin": return "zeroin";
                case "fire emblem seisen no keifu": return "fire emblem seisen no keifu";
                case "s-cry-ed": return "s-cry-ed";
                case "natsumes book of friends": return "natsumes book of friends";
                case "galaxy fight": return "galaxy fight";
                case "photo kano": return "photo kano";
                case "fortune arterial": return "fortune arterial";
                case "martial champion": return "martial champion";
                case "atelier series": return "atelier series";
                case "klonoa": return "klonoa";
                case "rage of bahamut": return "rage of bahamut";
                case "future gpx cyber formula": return "future gpx cyber formula";
                case "tactics ogre": return "tactics ogre";
                case "ginga e kickoff": return "ginga e kickoff";
                case "yat space travel agency": return "yat space travel agency";
                case "tonari no miko-san wa minna warau": return "tonari no miko-san wa minna warau";
                case "star ocean 4": return "star ocean 4";
                case "godannar": return "godannar";
                case "prunus girl": return "prunus girl";
                case "burst angel": return "burst angel";
                case "kiss x sis": return "kiss x sis";
                case "chrono trigger": return "chrono trigger";
                case "yume no crayon oukoku": return "yume no crayon oukoku";
                case "vampire princess miyu": return "vampire princess miyu";
                case "bible black": return "bible black";
                case "breath of fire": return "breath of fire";
                case "fukai ni nemuru oujo no abaddon": return "fukai ni nemuru oujo no abaddon";
                case "nier": return "nier";
                case "emma a victorian romance": return "emma a victorian romance";
                case "3x3 eyes": return "3x3 eyes";
                case "jungle wa itsumo hare nochi guu": return "jungle wa itsumo hare nochi guu";
                case "spider-man": return "spider-man";
                case "the ring": return "the ring";
                case "mayoi neko overrun": return "mayoi neko overrun";
                case "ikoku meiro no croisee": return "ikoku meiro no croisee";
                case "adventure time": return "adventure time";
                case "space pirate captain harlock": return "space pirate captain harlock";
                case "eiken": return "eiken";
                case "hajimete no orusuban": return "hajimete no orusuban";
                case "morenatsu": return "morenatsu";
                case "kodomo no omocha": return "kodomo no omocha";
                case "wild arms": return "wild arms";
                case "kurogane no linebarrels": return "kurogane no linebarrels";
                case "dragon quest vii": return "dragon quest vii";
                case "mermaid melody pichi pichi pitch": return "mermaid melody pichi pichi pitch";
                case "romancing saga": return "romancing saga";
                case "knights of ramune": return "knights of ramune";
                case "catherine": return "catherine";
                case "netoge no yome wa onnanoko ja nai to omotta": return "netoge no yome wa onnanoko ja nai to omotta";
                case "combattler v": return "combattler v";
                case "ixion saga dt": return "ixion saga dt";
                case "kaiji": return "kaiji";
                case "lost universe": return "lost universe";
                case "genmu senki leda": return "genmu senki leda";
                case "discipline": return "discipline";
                case "strawberry panic": return "strawberry panic";
                case "kokoro connect": return "kokoro connect";
                case "ninja gaiden": return "ninja gaiden";
                case "no-rin": return "no-rin";
                case "mikakunin de shinkoukei": return "mikakunin de shinkoukei";
                case "closers": return "closers";
                case "machine robo rescue": return "machine robo rescue";
                case "legendz": return "legendz";
                case "gunsmith cats": return "gunsmith cats";
                case "final fantasy iii": return "final fantasy iii";
                case "mahou no yousei persia": return "mahou no yousei persia";
                case "spirited away": return "spirited away";
                case "mahou shoujo ikusei keikaku": return "mahou shoujo ikusei keikaku";
                case "the last blade": return "the last blade";
                case "heavens memo pad": return "heavens memo pad";
                case "brave express might gaine": return "brave express might gaine";
                case "umi monogatari": return "umi monogatari";
                case "digimon xros wars": return "digimon xros wars";
                case "kakegurui": return "kakegurui";
                case "idolish7": return "idolish7";
                case "pastel yumi": return "pastel yumi";
                case "steel angel kurumi": return "steel angel kurumi";
                case "warzard": return "warzard";
                case "selector infected wixoss": return "selector infected wixoss";
                case "yumeria": return "yumeria";
                case "la blue girl": return "la blue girl";
                case "bubblegum crisis": return "bubblegum crisis";
                case "kisei juui suzune": return "kisei juui suzune";
                case "banner of the stars": return "banner of the stars";
                case "waku waku 7": return "waku waku 7";
                case "tasogare otome x amnesia": return "tasogare otome x amnesia";
                case "rwby": return "rwby";
                case "mob psycho 100": return "mob psycho 100";
                case "world of warcraft": return "world of warcraft";
                case "ganbare goemon": return "ganbare goemon";
                case "metal gear solid": return "metal gear solid";
                case "gingitsune": return "gingitsune";
                case "figure 17": return "figure 17";
                case "kyonyuu fantasy": return "kyonyuu fantasy";
                case "angel blade": return "angel blade";
                case "devil survivor": return "devil survivor";
                case "kyuushu sentai danjija": return "kyuushu sentai danjija";
                case "manabi straight": return "manabi straight";
                case "hyakka ryouran samurai girls": return "hyakka ryouran samurai girls";
                case "super dimensional legend rall": return "super dimensional legend rall";
                case "one kagayaku kisetsu e": return "one kagayaku kisetsu e";
                case "south park": return "south park";
                case "kekko kamen": return "kekko kamen";
                case "ikusa otome valkyrie": return "ikusa otome valkyrie";
                case "dororon enma-kun": return "dororon enma-kun";
                case "battle arena toshinden": return "battle arena toshinden";
                case "shuukan watashi no onii-chan": return "shuukan watashi no onii-chan";
                case "true love story": return "true love story";
                case "tenshi ni narumon": return "tenshi ni narumon";
                case "kikis delivery service": return "kikis delivery service";
                case "uma musume pretty derby": return "uma musume pretty derby";
                case "world heroes": return "world heroes";
                case "kashimashi": return "kashimashi";
                case "mahou senshi sweet knights": return "mahou senshi sweet knights";
                case "the super dimension fortress macross": return "the super dimension fortress macross";
                case "barakamon": return "barakamon";
                case "one week friends": return "one week friends";
                case "chrono crusade": return "chrono crusade";
                case "gokujou seitokai": return "gokujou seitokai";
                case "ukagaka": return "ukagaka";
                case "azuki-chan": return "azuki-chan";
                case "baby princess": return "baby princess";
                case "dangaioh": return "당가이오";
                case "no. 6": return "no. 6";
                case "unlight": return "unlight";
                case "in white": return "in white";
                case "princess maker": return "princess maker";
                case "outlanders": return "outlanders";
                case "onii-chan dakedo ai sae areba kankeinai yo ne": return "onii-chan dakedo ai sae areba kankeinai yo ne";
                case "mobile suit gundam the 08th ms team": return "mobile suit gundam the 08th ms team";
                case "romeos blue skies": return "romeos blue skies";
                case "toward the terra": return "toward the terra";
                case "marmalade boy": return "marmalade boy";
                case "shadow lady": return "shadow lady";
                case "ma ga ochiru yoru": return "ma ga ochiru yoru";
                case "diebuster": return "diebuster";
                case "futakoi": return "futakoi";
                case "happiness": return "happiness";
                case "otoyomegatari": return "otoyomegatari";
                case "birdy the mighty": return "birdy the mighty";
                case "sky girls": return "sky girls";
                case "macross": return "macross";
                case "shadowverse": return "shadowverse";
                case "hyakko": return "hyakko";
                case "the elder scrolls": return "the elder scrolls";
                case "rail wars": return "rail wars";
                case "magical antique": return "magical antique";
                case "kill me baby": return "kill me baby";
                case "kannazuki no miko": return "kannazuki no miko";
                case "net ghost pipopa": return "net ghost pipopa";
                case ".hacksign": return ".hacksign";
                case "genji tsuushin agedama": return "genji tsuushin agedama";
                case "starless": return "starless";
                case "doukyuusei 2": return "doukyuusei 2";
                case "tales of destiny 2": return "tales of destiny 2";
                case "xxxholic": return "xxxholic";
                case "amano megumi ha sukidarake": return "amano megumi ha sukidarake";
                case "grisaia no kajitsu": return "grisaia no kajitsu";
                case "mashiro iro symphony": return "mashiro iro symphony";
                case "magical halloween": return "magical halloween";
                case "monster rancher": return "monster rancher";
                case "elfen lied": return "elfen lied";
                case "parasite eve": return "parasite eve";
                case "hokenshitsu no shinigami": return "hokenshitsu no shinigami";
                case "dragon quest yuusha abel densetsu": return "dragon quest yuusha abel densetsu";
                case "the powerpuff girls": return "the powerpuff girls";
                case "valkyrie drive": return "valkyrie drive";
                case "floral magician mary bell": return "floral magician mary bell";
                case "kono bijutsubu ni wa mondai ga aru": return "kono bijutsubu ni wa mondai ga aru";
                case "infinite ryvius": return "infinite ryvius";
                case "omoikkiri kagaku adventure sou nanda": return "omoikkiri kagaku adventure sou nanda";
                case "shining force": return "shining force";
                case "chaos breaker": return "chaos breaker";
                case "tonde buurin": return "tonde buurin";
                case "sakura quest": return "sakura quest";
                case "kemeko deluxe": return "kemeko deluxe";
                case "narutaru": return "narutaru";
                case "uninhabited planet survive": return "uninhabited planet survive";
                case "licca vignette": return "licca vignette";
                case "gatchaman": return "gatchaman";
                case "suikoden": return "suikoden";
                case "youkoso jitsuryoku shijou shugi no kyoushitsu e": return "youkoso jitsuryoku shijou shugi no kyoushitsu e";
                case "madan no ou to vanadis": return "madan no ou to vanadis";
                case "bang dream": return "bang dream";
            }
            return eng_series;
        }
    }
}
